# Generated by Django 5.2.8 on 2025-11-29 14:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vocab', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('level', models.CharField(choices=[('N5', 'JLPT N5'), ('N4', 'JLPT N4'), ('N3', 'JLPT N3'), ('N2', 'JLPT N2'), ('N1', 'JLPT N1')], max_length=2)),
                ('category', models.CharField(choices=[('MOJI', 'Moji・Goi'), ('BUN', 'Bunpou'), ('MIX', 'Mixed')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('total_lessons', models.PositiveIntegerField(default=0, help_text='Số bài / ngày (optional)')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExamTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('level', models.CharField(choices=[('N5', 'JLPT N5'), ('N4', 'JLPT N4'), ('N3', 'JLPT N3'), ('N2', 'JLPT N2'), ('N1', 'JLPT N1')], max_length=2)),
                ('category', models.CharField(choices=[('MOJI', 'Moji・Goi'), ('BUN', 'Bunpou'), ('MIX', 'Mixed')], max_length=10)),
                ('group_type', models.CharField(choices=[('SINGLE', 'Bài lẻ / đề MOGI'), ('PATTERN', 'Theo dạng câu (Kanji đọc, từ cận nghĩa...)'), ('DAY', 'Học theo ngày (Day 01, Day 02...)')], default='SINGLE', help_text='Bài lẻ / theo dạng / theo ngày', max_length=20)),
                ('lesson_index', models.PositiveIntegerField(default=1)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('main_question_type', models.CharField(blank=True, choices=[('MCQ', 'Trắc nghiệm 4 lựa chọn'), ('ORDER', 'Sắp xếp câu'), ('FILL', 'Điền chỗ trống'), ('PAIR', 'Ghép từ'), ('NEAR', 'Từ cận nghĩa'), ('USAGE', 'Cách dùng từ'), ('PARA', 'Đoạn văn')], help_text='Loại câu chính của bài (nếu đồng nhất)', max_length=20)),
                ('time_limit_minutes', models.PositiveIntegerField(blank=True, help_text='Giới hạn thời gian (phút). Để trống nếu không giới hạn.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(blank=True, help_text='Để trống nếu là bài lẻ / đề MOGI', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='exam.exambook')),
            ],
            options={
                'ordering': ['book_id', 'group_type', 'lesson_index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('question_type', models.CharField(choices=[('MCQ', 'Trắc nghiệm 4 lựa chọn'), ('ORDER', 'Sắp xếp câu'), ('FILL', 'Điền chỗ trống'), ('PAIR', 'Ghép từ'), ('NEAR', 'Từ cận nghĩa'), ('USAGE', 'Cách dùng từ'), ('PARA', 'Đoạn văn')], default='MCQ', max_length=20)),
                ('text', models.TextField(help_text='Câu hỏi JP. Với sắp xếp câu có thể dùng ( ) (＊) để minh hoạ.')),
                ('explanation_vi', models.TextField(blank=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('correct_answer', models.CharField(max_length=100)),
                ('source', models.CharField(blank=True, help_text='VD: Power Drill N2 DAY 01', max_length=100)),
                ('mondai', models.CharField(blank=True, help_text="VD: '01', '02'...", max_length=20)),
                ('order_in_mondai', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exam.examtemplate')),
            ],
            options={
                'ordering': ['template_id', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'Đang làm'), ('submitted', 'Đã nộp')], default='in_progress', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_attempts', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='exam.examtemplate')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_answer', models.JSONField(default=dict)),
                ('is_correct', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exam.examattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.examquestion')),
            ],
            options={
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
