# Generated by Django 5.2.8 on 2025-11-30 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exambook',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Ảnh bìa sách hiển thị trên UI (tùy chọn).', null=True, upload_to='exam/book_covers/'),
        ),
    ]
