# Generated by Django 5.2.8 on 2025-11-30 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_exambook_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exambook',
            name='slug',
            field=models.SlugField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='examtemplate',
            name='slug',
            field=models.SlugField(max_length=120, unique=True),
        ),
    ]
