# Generated by Django 5.2.8 on 2025-12-01 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_alter_exambook_slug_alter_examtemplate_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingPassage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, help_text='Thứ tự passage trong bài')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('text', models.TextField(help_text='Đoạn văn JP đầy đủ')),
                ('data', models.JSONField(blank=True, default=dict)),
                ('template', models.ForeignKey(help_text='Passage thuộc bài test nào', on_delete=django.db.models.deletion.CASCADE, related_name='passages', to='exam.examtemplate')),
            ],
            options={
                'ordering': ['template_id', 'order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='examquestion',
            name='passage',
            field=models.ForeignKey(blank=True, help_text='Nếu là câu dokkai thì gắn với passage tương ứng', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='exam.readingpassage'),
        ),
    ]
