# Generated by Django 5.2.8 on 2025-12-01 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_readingpassage_examquestion_passage'),
    ]

    operations = [
        migrations.AddField(
            model_name='examquestion',
            name='audio',
            field=models.FileField(blank=True, help_text='File audio cho câu hỏi nghe (nếu có).', null=True, upload_to='exam/listening/'),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='audio_meta',
            field=models.JSONField(blank=True, default=dict, help_text='VD: {"cd": "CD1", "track": "03"}'),
        ),
        migrations.AlterField(
            model_name='exambook',
            name='category',
            field=models.CharField(choices=[('MOJI', 'Moji・Goi'), ('BUN', 'Bunpou'), ('DOKKAI', 'Dokkai'), ('CHOUKAI', 'Choukai'), ('MIX', 'Mixed')], max_length=10),
        ),
        migrations.AlterField(
            model_name='examtemplate',
            name='category',
            field=models.CharField(choices=[('MOJI', 'Moji・Goi'), ('BUN', 'Bunpou'), ('DOKKAI', 'Dokkai'), ('CHOUKAI', 'Choukai'), ('MIX', 'Mixed')], max_length=10),
        ),
    ]
