# Generated by Django 5.2.8 on 2025-12-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_examquestion_audio_examquestion_audio_meta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examquestion',
            name='text',
            field=models.TextField(blank=True, help_text='Câu hỏi JP. Với sắp xếp câu có thể dùng ( ) (＊) để minh hoạ.'),
        ),
    ]
