# Generated by Django 5.2.8 on 2025-12-01 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_alter_examquestion_text'),
    ]

    operations = [
        # Removed: vocab_items field was already excluded from initial migration
    ]
