# Generated by Django 5.2.8 on 2025-12-01 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_alter_examquestion_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examquestion',
            name='vocab_items',
        ),
    ]
