# Generated by Django 5.2.8 on 2025-12-03 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_remove_examquestion_vocab_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exambook',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
    ]
