# Generated by Django 5.2.8 on 2025-12-04 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_alter_exambook_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='examtemplate',
            name='dokkai_skill',
            field=models.CharField(blank=True, help_text='Tag skill đọc hiểu (VD: 内容理解 / 情報検索 / 主旨把握...)', max_length=50),
        ),
        migrations.AddField(
            model_name='examtemplate',
            name='reading_format',
            field=models.CharField(blank=True, choices=[('SHORT', '短文'), ('MIDDLE', '中文'), ('LONG', '長文'), ('MAIL', 'メール文'), ('INFO', '情報検索')], help_text='Dùng cho đọc hiểu: 短文 / 中文 / 長文 / メール / 情報検索', max_length=10),
        ),
    ]
