# Generated by Django 5.2.8 on 2025-12-04 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_examtemplate_dokkai_skill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examtemplate',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
    ]
