# Generated by Django 5.2.8 on 2025-12-04 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_alter_examtemplate_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingpassage',
            name='image',
            field=models.ImageField(blank=True, help_text='Ảnh poster / bảng thông tin cho dokkai (nếu có).', null=True, upload_to='exam/dokkai_passages/'),
        ),
    ]
