# Generated by Django 5.2.8 on 2025-12-28 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0011_readingpassage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='examquestion',
            name='image',
            field=models.ImageField(blank=True, help_text='Hình ảnh cho Listening Part 1 hoặc Reading Part 7 (nếu có).', null=True, upload_to='exam/toeic/images/'),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='toeic_part',
            field=models.CharField(blank=True, choices=[('L1', 'Listening Part 1: Mô tả hình ảnh'), ('L2', 'Listening Part 2: Câu hỏi-Đáp án'), ('L3', 'Listening Part 3: Hội thoại ngắn'), ('L4', 'Listening Part 4: Bài nói ngắn'), ('R5', 'Reading Part 5: Điền từ vào câu'), ('R6', 'Reading Part 6: Điền từ vào đoạn văn'), ('R7', 'Reading Part 7: Đọc hiểu')], help_text='Phần TOEIC (L1-L4, R5-R7). Để trống nếu không phải TOEIC.', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='examtemplate',
            name='is_full_toeic',
            field=models.BooleanField(default=False, help_text='True nếu là full test TOEIC (200 câu: Listening + Reading)'),
        ),
        migrations.AddField(
            model_name='examtemplate',
            name='listening_time_limit_minutes',
            field=models.PositiveIntegerField(blank=True, default=45, help_text='Giới hạn thời gian cho phần Listening (phút). Mặc định 45 phút.', null=True),
        ),
        migrations.AddField(
            model_name='examtemplate',
            name='reading_time_limit_minutes',
            field=models.PositiveIntegerField(blank=True, default=75, help_text='Giới hạn thời gian cho phần Reading (phút). Mặc định 75 phút.', null=True),
        ),
        migrations.AlterField(
            model_name='exambook',
            name='category',
            field=models.CharField(choices=[('MOJI', 'Moji・Goi'), ('BUN', 'Bunpou'), ('DOKKAI', 'Dokkai'), ('CHOUKAI', 'Choukai'), ('MIX', 'Mixed'), ('LISTENING', 'TOEIC Listening'), ('READING', 'TOEIC Reading'), ('TOEIC_FULL', 'TOEIC Full Test')], max_length=10),
        ),
        migrations.AlterField(
            model_name='exambook',
            name='level',
            field=models.CharField(choices=[('N5', 'JLPT N5'), ('N4', 'JLPT N4'), ('N3', 'JLPT N3'), ('N2', 'JLPT N2'), ('N1', 'JLPT N1'), ('TOEIC', 'TOEIC')], max_length=10),
        ),
        migrations.AlterField(
            model_name='examtemplate',
            name='category',
            field=models.CharField(choices=[('MOJI', 'Moji・Goi'), ('BUN', 'Bunpou'), ('DOKKAI', 'Dokkai'), ('CHOUKAI', 'Choukai'), ('MIX', 'Mixed'), ('LISTENING', 'TOEIC Listening'), ('READING', 'TOEIC Reading'), ('TOEIC_FULL', 'TOEIC Full Test')], max_length=10),
        ),
        migrations.AlterField(
            model_name='examtemplate',
            name='level',
            field=models.CharField(choices=[('N5', 'JLPT N5'), ('N4', 'JLPT N4'), ('N3', 'JLPT N3'), ('N2', 'JLPT N2'), ('N1', 'JLPT N1'), ('TOEIC', 'TOEIC')], max_length=10),
        ),
        migrations.CreateModel(
            name='ListeningConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toeic_part', models.CharField(choices=[('L3', 'Part 3'), ('L4', 'Part 4')], help_text='Part 3 (hội thoại) hoặc Part 4 (bài nói)', max_length=2)),
                ('order', models.PositiveIntegerField(default=1, help_text='Thứ tự đoạn trong Part (1-13 cho Part 3, 1-10 cho Part 4)')),
                ('audio', models.FileField(help_text='File audio cho đoạn hội thoại/bài nói', upload_to='exam/toeic/listening/')),
                ('image', models.ImageField(blank=True, help_text='Hình/biểu đồ kèm theo (nếu có)', null=True, upload_to='exam/toeic/listening_images/')),
                ('transcript', models.TextField(blank=True, help_text='Transcript của đoạn audio (hiển thị sau khi submit)')),
                ('data', models.JSONField(blank=True, default=dict, help_text='VD: {"speakers": 2, "topic": "office meeting", "duration_seconds": 45}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(help_text='Template chứa đoạn hội thoại này', on_delete=django.db.models.deletion.CASCADE, related_name='listening_conversations', to='exam.examtemplate')),
            ],
            options={
                'verbose_name': 'Listening Conversation',
                'verbose_name_plural': 'Listening Conversations',
                'ordering': ['template_id', 'toeic_part', 'order', 'id'],
                'unique_together': {('template', 'toeic_part', 'order')},
            },
        ),
        migrations.AddField(
            model_name='examquestion',
            name='listening_conversation',
            field=models.ForeignKey(blank=True, help_text='Đoạn hội thoại/bài nói cho Listening Part 3, 4 (nếu có).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='exam.listeningconversation'),
        ),
    ]
