# Generated by Django 5.2.8 on 2025-12-30 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0012_add_toeic_support'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Nội dung comment (tối đa 2000 ký tự)', max_length=2000)),
                ('is_active', models.BooleanField(default=True, help_text='Admin có thể ẩn comment không phù hợp')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(help_text='Đề thi được comment', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='exam.examtemplate')),
                ('user', models.ForeignKey(help_text='User đã comment', on_delete=django.db.models.deletion.CASCADE, related_name='exam_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['template', '-created_at'], name='exam_examco_templat_d2ad91_idx')],
            },
        ),
    ]
