# Generated by Django 5.2.8 on 2025-12-31 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0013_examcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='data',
            field=models.JSONField(blank=True, default=dict, help_text='Lưu metadata như mode, selected_parts, time_limit_minutes'),
        ),
    ]
