# Generated by Django 5.2.8 on 2026-01-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0014_examattempt_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='examtemplate',
            name='audio_file',
            field=models.FileField(blank=True, help_text='File audio trọn bài (dùng cho TOEIC Full Test hoặc bài nghe dài).', null=True, upload_to='exam/audio/'),
        ),
    ]
