# Generated by Django 5.2.8 on 2026-01-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0017_readingpassage_content_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingpassage',
            name='instruction',
            field=models.TextField(blank=True, help_text='Hướng dẫn đọc hiểu (optional)'),
        ),
    ]
