# Generated by Django 5.2.8 on 2026-01-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0018_readingpassage_instruction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingpassage',
            name='text',
            field=models.TextField(blank=True, help_text='Đoạn văn JP đầy đủ'),
        ),
    ]
