# Generated by Django 5.2.8 on 2026-01-15 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0020_examquestion_explanation_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='examquestion',
            name='audio_transcript',
            field=models.TextField(blank=True, help_text='Transcript của audio (cho Part 1/2)'),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='audio_transcript_vi',
            field=models.TextField(blank=True, help_text='Bản dịch tiếng Việt của audio transcript'),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='text_vi',
            field=models.TextField(blank=True, help_text='Bản dịch tiếng Việt của câu hỏi'),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='transcript_data',
            field=models.JSONField(blank=True, default=dict, help_text='Bilingual options/transcript: {"options": [{"label":"A","text":"...","text_vi":"..."}]}'),
        ),
        migrations.AddField(
            model_name='listeningconversation',
            name='transcript_data',
            field=models.JSONField(blank=True, default=dict, help_text='Bilingual transcript: {"lines": [{"speaker": "M", "text": "...", "text_vi": "..."}]}'),
        ),
        migrations.AddField(
            model_name='listeningconversation',
            name='transcript_vi',
            field=models.TextField(blank=True, help_text='Bản dịch tiếng Việt của transcript'),
        ),
        migrations.AlterField(
            model_name='examquestion',
            name='text',
            field=models.TextField(blank=True, help_text='Câu hỏi. Với sắp xếp câu có thể dùng ( ) (＊) để minh hoạ.'),
        ),
    ]
