# Generated by Django 5.2.8 on 2026-02-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0021_add_bilingual_transcript_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examquestion",
            name="audio",
            field=models.FileField(
                blank=True,
                help_text="File audio cho câu hỏi nghe (nếu có).",
                max_length=500,
                null=True,
                upload_to="exam/listening/",
            ),
        ),
        migrations.AlterField(
            model_name="examquestion",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Hình ảnh cho Listening Part 1 hoặc Reading Part 7 (nếu có).",
                max_length=500,
                null=True,
                upload_to="exam/toeic/images/",
            ),
        ),
    ]
