# Generated by Django 5.2.8 on 2026-03-03 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0022_increase_file_field_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exambook',
            name='category',
            field=models.CharField(choices=[('MOJI', 'Moji・Goi'), ('BUN', 'Bunpou'), ('DOKKAI', 'Dokkai'), ('CHOUKAI', 'Choukai'), ('MIX', 'Mixed'), ('LISTENING', 'TOEIC Listening'), ('READING', 'TOEIC Reading'), ('TOEIC_FULL', 'TOEIC Full Test'), ('ENGLISH', 'English Practice')], max_length=10),
        ),
        migrations.AlterField(
            model_name='exambook',
            name='level',
            field=models.CharField(choices=[('N5', 'JLPT N5'), ('N4', 'JLPT N4'), ('N3', 'JLPT N3'), ('N2', 'JLPT N2'), ('N1', 'JLPT N1'), ('TOEIC', 'TOEIC'), ('EN10', 'English Lớp 10')], max_length=10),
        ),
        migrations.AlterField(
            model_name='examtemplate',
            name='category',
            field=models.CharField(choices=[('MOJI', 'Moji・Goi'), ('BUN', 'Bunpou'), ('DOKKAI', 'Dokkai'), ('CHOUKAI', 'Choukai'), ('MIX', 'Mixed'), ('LISTENING', 'TOEIC Listening'), ('READING', 'TOEIC Reading'), ('TOEIC_FULL', 'TOEIC Full Test'), ('ENGLISH', 'English Practice')], max_length=10),
        ),
        migrations.AlterField(
            model_name='examtemplate',
            name='level',
            field=models.CharField(choices=[('N5', 'JLPT N5'), ('N4', 'JLPT N4'), ('N3', 'JLPT N3'), ('N2', 'JLPT N2'), ('N1', 'JLPT N1'), ('TOEIC', 'TOEIC'), ('EN10', 'English Lớp 10')], max_length=10),
        ),
    ]
