# Generated by Django 5.2.8 on 2026-03-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0024_add_exam_review_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='examtemplate',
            name='is_public',
            field=models.BooleanField(default=False, help_text='True = mở cho tất cả, False = chỉ VIP mới truy cập được.'),
        ),
    ]
