# Generated by Django 5.2.8 on 2026-03-06 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0025_add_is_public_to_examtemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='EN10GrammarTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_id', models.SlugField(help_text='VD: nouns, tenses, passive-voice', unique=True)),
                ('title', models.CharField(help_text='Tên tiếng Anh: Nouns', max_length=100)),
                ('title_vi', models.CharField(help_text='Tên tiếng Việt: Danh từ', max_length=100)),
                ('emoji', models.CharField(default='📝', max_length=10)),
                ('description', models.TextField(blank=True, help_text='Mô tả ngắn về chủ đề')),
                ('difficulty', models.CharField(choices=[('easy', 'Cơ bản'), ('medium', 'Trung bình'), ('hard', 'Nâng cao')], default='easy', max_length=10)),
                ('order', models.PositiveIntegerField(default=0, help_text='Thứ tự hiển thị')),
                ('sections', models.JSONField(blank=True, default=list, help_text='[{"heading": "...", "content": "..."}]')),
                ('formulas', models.JSONField(blank=True, default=list, help_text='[{"name": "...", "formula": "...", "example": "...", "exampleVi": "..."}]')),
                ('exercises', models.JSONField(blank=True, default=list, help_text='[{"question": "...", "options": [...], "correct": 0, "explanation": "..."}]')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'EN10 Grammar Topic',
                'verbose_name_plural': 'EN10 Grammar Topics',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EN10PhrasalVerbSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Phrasal Verbs', max_length=100)),
                ('verbs', models.JSONField(blank=True, default=list, help_text='[{"id": 1, "verb": "turn off", ...}]')),
                ('fill_sentences', models.JSONField(blank=True, default=list, help_text='[{"sentence": "...", "answer": "...", "hint": "..."}]')),
                ('quiz_questions', models.JSONField(blank=True, default=list, help_text='[{"question": "...", "options": [...], "correct": 0}]')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'EN10 Phrasal Verb Set',
                'verbose_name_plural': 'EN10 Phrasal Verb Sets',
            },
        ),
    ]
