# Generated by Django 5.2.8 on 2026-03-06 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0026_add_en10_grammar_phrasal'),
    ]

    operations = [
        migrations.CreateModel(
            name='EN10VocabTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='VD: education, health', max_length=60, unique=True)),
                ('title', models.CharField(help_text='Education', max_length=100)),
                ('title_vi', models.CharField(help_text='Giáo dục', max_length=100)),
                ('emoji', models.CharField(default='📚', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('words', models.JSONField(blank=True, default=list, help_text='[{"word": "...", "pos": "noun", "ipa": "/.../" , "meaning": "..."}]')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'EN10 Vocab Topic',
                'verbose_name_plural': 'EN10 Vocab Topics',
                'ordering': ['order', 'id'],
            },
        ),
    ]
