# Generated by Django 5.2.8 on 2026-03-06 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0027_add_en10_vocab_topic'),
        ('vocab', '0026_add_review_log_to_fsrs'),
    ]

    operations = [
        migrations.AddField(
            model_name='en10vocabtopic',
            name='vocabularies',
            field=models.ManyToManyField(blank=True, help_text='Linked Vocabulary records (primary source)', related_name='en10_topics', to='vocab.vocabulary'),
        ),
    ]
