# Generated by Django 5.2.8 on 2026-03-07 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0028_add_vocabularies_m2m_to_en10vocabtopic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EN10VocabProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learned_words', models.JSONField(blank=True, default=list, help_text='List of learned word strings, e.g. ["education", "school"]')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='exam.en10vocabtopic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='en10_vocab_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'EN10 Vocab Progress',
                'verbose_name_plural': 'EN10 Vocab Progress',
                'unique_together': {('user', 'topic')},
            },
        ),
    ]
