import os
import django
from django.db import connection

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.settings')
django.setup()

def fix_missing_tables():
    """
    Recreates missing vocab_vocabularyset and vocab_setitem tables.
    Uses schema from 0001_initial.py.
    """
    sql_creates = [
        """
        CREATE TABLE IF NOT EXISTS vocab_vocabularyset (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            title varchar(255) NOT NULL,
            description text NOT NULL,
            is_public boolean NOT NULL,
            status varchar(20) NOT NULL,
            created_at timestamp with time zone NOT NULL,
            updated_at timestamp with time zone NOT NULL,
            owner_id bigint NULL REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED
        );
        """,
        """
        CREATE INDEX IF NOT EXISTS vocab_vocabularyset_owner_id_idx ON vocab_vocabularyset(owner_id);
        """,
        """
        CREATE TABLE IF NOT EXISTS vocab_setitem (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            display_order integer NOT NULL,
            created_at timestamp with time zone NOT NULL,
            definition_id bigint NOT NULL REFERENCES vocab_worddefinition(id) DEFERRABLE INITIALLY DEFERRED,
            vocabulary_set_id bigint NOT NULL REFERENCES vocab_vocabularyset(id) DEFERRABLE INITIALLY DEFERRED
        );
        """,
        """
        CREATE INDEX IF NOT EXISTS vocab_setitem_definition_id_idx ON vocab_setitem(definition_id);
        """,
        """
        CREATE INDEX IF NOT EXISTS vocab_setitem_vocabulary_set_id_idx ON vocab_setitem(vocabulary_set_id);
        """
    ]

    print("Checking and fixing missing tables...")
    with connection.cursor() as cursor:
        # Check if vocabularyset exists
        cursor.execute("SELECT to_regclass('vocab_vocabularyset');")
        if cursor.fetchone()[0] is None:
            print("vocab_vocabularyset is MISSING. Recreating...")
            for sql in sql_creates[:2]: # First 2 stmts
                cursor.execute(sql)
            print("vocab_vocabularyset created.")
        else:
            print("vocab_vocabularyset already exists.")

        # Check if setitem exists
        cursor.execute("SELECT to_regclass('vocab_setitem');")
        if cursor.fetchone()[0] is None:
            print("vocab_setitem is MISSING. Recreating...")
            for sql in sql_creates[2:]: # Remaining stmts
                cursor.execute(sql)
            print("vocab_setitem created.")
        else:
            print("vocab_setitem already exists.")
            
    print("Fix complete. Now run 'python manage.py migrate' to apply remaining migrations.")

if __name__ == "__main__":
    fix_missing_tables()
