# Generated by Django 5.2.8 on 2025-12-27 03:18

import django.db.models.deletion
from django.db import migrations, models


def forwards_move_lesson_course_to_section(apps, schema_editor):
    Course = apps.get_model("core", "Course")
    Section = apps.get_model("core", "Section")
    Lesson = apps.get_model("core", "Lesson")

    # Create a default Section per Course that currently has lessons,
    # then assign those lessons to the new Section.
    for course in Course.objects.all():
        lessons = Lesson.objects.filter(course_id=course.id)
        if not lessons.exists():
            continue

        section, _created = Section.objects.get_or_create(
            course_id=course.id,
            title="General",
            defaults={"order": 0, "is_active": True},
        )
        lessons.update(section_id=section.id)


def backwards_move_section_to_course(apps, schema_editor):
    Lesson = apps.get_model("core", "Lesson")
    for lesson in Lesson.objects.select_related("section").all():
        if lesson.section_id:
            lesson.course_id = lesson.section.course_id
            lesson.save(update_fields=["course"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['section__course__order', 'section__order', 'order', 'title'], 'verbose_name': 'Lesson', 'verbose_name_plural': 'Lessons'},
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=240, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.course')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'ordering': ['course__order', 'order', 'title'],
                'unique_together': {('course', 'title')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='lesson',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='core.section'),
        ),
        migrations.RunPython(forwards_move_lesson_course_to_section, backwards_move_section_to_course),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('section', 'title')},
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='course',
        ),
    ]
