# Generated by Django 5.2.8 on 2025-12-31 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_lesson_options_section_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DictationExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Tiêu đề bài tập', max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=240, unique=True)),
                ('description', models.TextField(blank=True, help_text='Mô tả bài tập')),
                ('audio_file', models.FileField(help_text='File audio cho bài dictation', upload_to='dictation/audio/')),
                ('audio_duration', models.FloatField(blank=True, help_text='Độ dài audio (giây)', null=True)),
                ('full_transcript', models.TextField(help_text='Transcript đầy đủ của audio (để so sánh với câu trả lời)')),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(blank=True, help_text='Bài tập này thuộc lesson nào (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dictation_exercises', to='core.lesson')),
            ],
            options={
                'verbose_name': 'Dictation Exercise',
                'verbose_name_plural': 'Dictation Exercises',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='DictationSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='Thứ tự segment trong bài')),
                ('start_time', models.FloatField(help_text='Thời điểm bắt đầu segment (giây)')),
                ('end_time', models.FloatField(help_text='Thời điểm kết thúc segment (giây)')),
                ('correct_text', models.TextField(help_text='Text đúng của segment này')),
                ('hint', models.TextField(blank=True, help_text='Gợi ý cho segment này (optional)')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='core.dictationexercise')),
            ],
            options={
                'verbose_name': 'Dictation Segment',
                'verbose_name_plural': 'Dictation Segments',
                'ordering': ['exercise', 'order'],
                'unique_together': {('exercise', 'order')},
            },
        ),
    ]
