# Generated by Django 5.2.8 on 2025-12-31 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_dictationexercise_dictationsegment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, help_text='Mô tả ngắn về khóa học'),
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, help_text='Ảnh đại diện cho khóa học', null=True, upload_to='courses/'),
        ),
    ]
