# Generated by Django 5.2.8 on 2026-01-07 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_enrollment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('TOEIC', 'TOEIC'), ('IELTS', 'IELTS'), ('JLPT_N5', 'JLPT N5'), ('JLPT_N4', 'JLPT N4'), ('JLPT_N3', 'JLPT N3'), ('JLPT_N2', 'JLPT N2'), ('JLPT_N1', 'JLPT N1')], default='TOEIC', help_text='Loại kỳ thi', max_length=20)),
                ('target_score', models.PositiveIntegerField(default=600, help_text='Điểm mục tiêu')),
                ('exam_date', models.DateField(blank=True, help_text='Ngày dự kiến thi', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exam_goal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exam Goal',
                'verbose_name_plural': 'Exam Goals',
            },
        ),
    ]
