# Generated by Django 5.2.8 on 2026-01-14 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_examgoal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DictationProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_segment', models.PositiveIntegerField(default=0)),
                ('total_segments', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to='core.dictationexercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dictation_progresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dictation Progress',
                'verbose_name_plural': 'Dictation Progresses',
                'unique_together': {('user', 'exercise')},
            },
        ),
    ]
