# Generated by Django 5.2.8 on 2026-01-29 02:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_dictationprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('first_step', 'First Step'), ('week_warrior', 'Week Warrior'), ('century', 'Century'), ('level_master', 'Level Master'), ('perfect_set', 'Perfect Set'), ('early_bird', 'Early Bird'), ('night_owl', 'Night Owl')], help_text='Mã badge (unique identifier)', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Tên hiển thị', max_length=100)),
                ('description', models.TextField(help_text='Mô tả điều kiện đạt được')),
                ('icon', models.CharField(help_text='Emoji icon', max_length=10)),
                ('order', models.PositiveIntegerField(default=0, help_text='Thứ tự hiển thị')),
            ],
            options={
                'verbose_name': 'Badge',
                'verbose_name_plural': 'Badges',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_by', to='core.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Badge',
                'verbose_name_plural': 'User Badges',
                'ordering': ['-earned_at'],
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
