# Generated by Django 5.2.8 on 2026-01-29 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_badge_userbadge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='code',
            field=models.CharField(choices=[('first_step', 'Bước Đầu Tiên'), ('week_warrior', 'Chiến Binh 7 Ngày'), ('streak_14', 'Kiên Trì'), ('streak_30', 'Thói Quen Vàng'), ('streak_60', 'Bất Khuất'), ('streak_100', 'Bậc Thầy Kỷ Luật'), ('streak_365', 'Huyền Thoại'), ('century', 'Trăm Từ'), ('vocab_500', 'Nhà Sưu Tầm'), ('vocab_1000', 'Kho Từ Vựng'), ('vocab_2000', 'Bách Khoa'), ('vocab_5000', 'Từ Điển Sống'), ('level_master', 'Chinh Phục Level'), ('perfect_set', 'Set Hoàn Hảo'), ('set_10', 'Học Viên Chăm Chỉ'), ('set_50', 'Master Từ Vựng'), ('review_master', 'Ôn Tập Siêu Đẳng'), ('first_exam', 'Thử Thách Đầu Tiên'), ('exam_10', 'Luyện Đề Chăm Chỉ'), ('exam_50', 'Chiến Binh Luyện Đề'), ('exam_100', 'Cao Thủ Luyện Đề'), ('perfect_exam', 'Điểm Tuyệt Đối'), ('high_score_80', 'Điểm Cao 80+'), ('high_score_90', 'Điểm Xuất Sắc'), ('speed_demon', 'Tốc Độ Ánh Sáng'), ('full_test', 'Thi Thật'), ('first_dictation', 'Lắng Nghe Đầu Tiên'), ('dictation_10', 'Tai Thính'), ('dictation_50', 'Bậc Thầy Nghe'), ('perfect_dictation', 'Chính Tả Hoàn Hảo'), ('listening_streak', 'Nghe Mỗi Ngày'), ('early_bird', 'Chim Sớm'), ('night_owl', 'Cú Đêm'), ('weekend_warrior', 'Chiến Binh Cuối Tuần'), ('lunch_learner', 'Học Giờ Nghỉ'), ('all_rounder', 'Toàn Diện'), ('comeback', 'Quay Lại'), ('perfectionist', 'Hoàn Hảo Chủ Nghĩa'), ('sharpshooter', 'Bắn Tỉa'), ('speed_learner', 'Học Nhanh')], help_text='Mã badge (unique identifier)', max_length=50, unique=True),
        ),
    ]
