# Generated by Django 5.2.8 on 2026-01-30 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_badge_code'),
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='Giới thiệu ngắn về bản thân', max_length=500)),
                ('display_title', models.CharField(blank=True, help_text='Tiêu đề hiển thị (VD: Hello Fellow < Love />! 👋)', max_length=100)),
                ('subtitle', models.CharField(blank=True, help_text='Phụ đề (VD: Welcome to my profile)', max_length=200)),
                ('avatar', models.ImageField(blank=True, help_text='Ảnh đại diện', null=True, upload_to='profiles/avatars/')),
                ('cover_image', models.ImageField(blank=True, help_text='Ảnh bìa', null=True, upload_to='profiles/covers/')),
                ('social_links', models.JSONField(blank=True, default=dict, help_text="Links mạng xã hội: {'facebook': 'url', 'tiktok': 'url', ...}")),
                ('info_items', models.JSONField(blank=True, default=list, help_text="Các mục thông tin: [{'icon': '👋', 'text': 'Hi, I'm...'}, ...]")),
                ('skills', models.JSONField(blank=True, default=dict, help_text="Kỹ năng: {'languages': ['English', ...], 'tools': [...], 'soft_skills': [...]}")),
                ('certificates', models.JSONField(blank=True, default=list, help_text="Chứng chỉ: [{'name': 'IELTS', 'score': '7.5'}, ...]")),
                ('hobbies', models.JSONField(blank=True, default=list, help_text="Sở thích: [{'icon': '🏔️', 'text': 'Traveling'}, ...]")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipped_frame', models.ForeignKey(blank=True, help_text='Khung avatar đang sử dụng', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_by', to='shop.avatarframe')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
