# Generated by Django 5.2.8 on 2026-02-15 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_add_user_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="study_language",
            field=models.CharField(
                choices=[("jp", "Japanese"), ("en", "English")],
                default="jp",
                help_text="Ngôn ngữ đang học: jp (Tiếng Nhật) hoặc en (Tiếng Anh)",
                max_length=5,
            ),
        ),
    ]
