# Generated by Django 5.2.8 on 2026-02-15 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_study_language_to_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictationexercise',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('jp', 'Japanese')], default='en', help_text='Ngôn ngữ của bài dictation', max_length=5),
        ),
    ]
