# Generated by Django 5.2.8 on 2026-01-30 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('target_score', models.IntegerField()),
                ('target_skills', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('progress_percentage', models.FloatField(default=0.0)),
                ('estimated_days', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_paths', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Learning Path',
                'verbose_name_plural': 'Learning Paths',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlacementQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(choices=[('L1', 'Listening - Photos'), ('L2', 'Listening - Question & Response'), ('L3', 'Listening - Conversations'), ('L4', 'Listening - Talks'), ('R5', 'Reading - Incomplete Sentences'), ('R6', 'Reading - Text Completion'), ('R7', 'Reading - Reading Comprehension'), ('VOC', 'Vocabulary'), ('GRM', 'Grammar')], db_index=True, max_length=3)),
                ('difficulty', models.IntegerField(choices=[(1, 'Beginner (10-295)'), (2, 'Elementary (300-395)'), (3, 'Intermediate (400-595)'), (4, 'Upper Intermediate (600-795)'), (5, 'Advanced (800-895)'), (6, 'Expert (900-990)')], db_index=True)),
                ('question_text', models.TextField()),
                ('question_audio', models.URLField(blank=True, null=True)),
                ('question_image', models.URLField(blank=True, null=True)),
                ('context_text', models.TextField(blank=True)),
                ('context_audio', models.URLField(blank=True, null=True)),
                ('option_a', models.CharField(max_length=500)),
                ('option_b', models.CharField(max_length=500)),
                ('option_c', models.CharField(max_length=500)),
                ('option_d', models.CharField(blank=True, max_length=500)),
                ('correct_answer', models.CharField(max_length=1)),
                ('explanation', models.TextField(blank=True, help_text='Giải thích đáp án đúng')),
                ('irt_difficulty', models.FloatField(default=0.0, help_text='b parameter (-3 to +3)')),
                ('irt_discrimination', models.FloatField(default=1.0, help_text='a parameter (0.5 to 2.5)')),
                ('irt_guessing', models.FloatField(default=0.25, help_text='c parameter')),
                ('times_shown', models.IntegerField(default=0)),
                ('times_correct', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Placement Question',
                'verbose_name_plural': 'Placement Questions',
                'indexes': [models.Index(fields=['skill', 'difficulty'], name='placement_p_skill_1896db_idx'), models.Index(fields=['irt_difficulty'], name='placement_p_irt_dif_cd2d33_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlacementTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='progress', max_length=10)),
                ('estimated_score', models.IntegerField(blank=True, null=True)),
                ('estimated_listening', models.IntegerField(blank=True, null=True)),
                ('estimated_reading', models.IntegerField(blank=True, null=True)),
                ('confidence_interval', models.IntegerField(default=50)),
                ('skill_scores', models.JSONField(default=dict)),
                ('current_ability', models.FloatField(default=0.0)),
                ('questions_answered', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_tests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Placement Test',
                'verbose_name_plural': 'Placement Tests',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PlacementAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.CharField(max_length=1)),
                ('is_correct', models.BooleanField()),
                ('time_spent', models.IntegerField(default=0)),
                ('ability_after', models.FloatField()),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placement.placementquestion')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='placement.placementtest')),
            ],
            options={
                'verbose_name': 'Placement Answer',
                'verbose_name_plural': 'Placement Answers',
                'ordering': ['answered_at'],
            },
        ),
        migrations.CreateModel(
            name='UserLearningProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_level', models.IntegerField(choices=[(1, 'Beginner (10-295)'), (2, 'Elementary (300-395)'), (3, 'Intermediate (400-595)'), (4, 'Upper Intermediate (600-795)'), (5, 'Advanced (800-895)'), (6, 'Expert (900-990)')], default=3)),
                ('estimated_score', models.IntegerField(default=450)),
                ('skill_proficiency', models.JSONField(default=dict)),
                ('weak_skills', models.JSONField(default=list)),
                ('strong_skills', models.JSONField(default=list)),
                ('target_score', models.IntegerField(blank=True, null=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('preferred_session_length', models.IntegerField(default=15)),
                ('best_learning_time', models.CharField(default='evening', max_length=20)),
                ('preferred_content_types', models.JSONField(default=list)),
                ('total_study_time', models.IntegerField(default=0)),
                ('total_questions_answered', models.IntegerField(default=0)),
                ('overall_accuracy', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learning_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Learning Profile',
                'verbose_name_plural': 'User Learning Profiles',
            },
        ),
        migrations.CreateModel(
            name='DailyLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('recommended_activities', models.JSONField(default=list)),
                ('completed_activities', models.JSONField(default=list)),
                ('target_minutes', models.IntegerField(default=30)),
                ('actual_minutes', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_lessons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Lesson',
                'verbose_name_plural': 'Daily Lessons',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='LearningMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('target_skill', models.CharField(blank=True, choices=[('L1', 'Listening - Photos'), ('L2', 'Listening - Question & Response'), ('L3', 'Listening - Conversations'), ('L4', 'Listening - Talks'), ('R5', 'Reading - Incomplete Sentences'), ('R6', 'Reading - Text Completion'), ('R7', 'Reading - Reading Comprehension'), ('VOC', 'Vocabulary'), ('GRM', 'Grammar')], max_length=3, null=True)),
                ('target_proficiency', models.FloatField(default=0.7)),
                ('vocabulary_set_ids', models.JSONField(default=list)),
                ('grammar_point_ids', models.JSONField(default=list)),
                ('exam_template_ids', models.JSONField(default=list)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_unlocked', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='placement.learningpath')),
            ],
            options={
                'verbose_name': 'Learning Milestone',
                'verbose_name_plural': 'Learning Milestones',
                'ordering': ['path', 'order'],
                'unique_together': {('path', 'order')},
            },
        ),
        migrations.CreateModel(
            name='SkillProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(choices=[('L1', 'Listening - Photos'), ('L2', 'Listening - Question & Response'), ('L3', 'Listening - Conversations'), ('L4', 'Listening - Talks'), ('R5', 'Reading - Incomplete Sentences'), ('R6', 'Reading - Text Completion'), ('R7', 'Reading - Reading Comprehension'), ('VOC', 'Vocabulary'), ('GRM', 'Grammar')], max_length=3)),
                ('date', models.DateField()),
                ('proficiency', models.FloatField()),
                ('questions_attempted', models.IntegerField(default=0)),
                ('questions_correct', models.IntegerField(default=0)),
                ('study_time', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Skill Progress',
                'verbose_name_plural': 'Skill Progress',
                'indexes': [models.Index(fields=['user', 'date'], name='placement_s_user_id_d0454f_idx')],
                'unique_together': {('user', 'skill', 'date')},
            },
        ),
    ]
