# Generated by Django 5.2.8 on 2025-12-26 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('grammar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grammarpoint',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grammar_points', to='core.course'),
        ),
        migrations.AddField(
            model_name='grammarpoint',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grammar_points', to='core.lesson'),
        ),
    ]
