# Generated by Django 5.2.8 on 2025-12-27 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_lesson_options_section_and_more'),
        ('grammar', '0002_grammarpoint_course_grammarpoint_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='grammarpoint',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grammar_points', to='core.section'),
        ),
    ]
