# Generated by Django 5.2.8 on 2026-02-19 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grammar", "0003_grammarpoint_section"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GrammarBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("N1", "N1"),
                            ("N2", "N2"),
                            ("N3", "N3"),
                            ("N4", "N4"),
                            ("N5", "N5"),
                        ],
                        default="N5",
                        max_length=2,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="grammar/books/"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Sách ngữ pháp",
                "verbose_name_plural": "Sách ngữ pháp",
                "ordering": ["level", "title"],
            },
        ),
        migrations.AlterModelOptions(
            name="grammarpoint",
            options={
                "ordering": ["level", "order", "title"],
                "verbose_name": "Ngữ pháp",
                "verbose_name_plural": "Ngữ pháp",
            },
        ),
        migrations.AddField(
            model_name="grammarpoint",
            name="explanation",
            field=models.TextField(blank=True, help_text="Giải thích chi tiết"),
        ),
        migrations.AddField(
            model_name="grammarpoint",
            name="formation",
            field=models.CharField(
                blank=True, help_text="Cấu trúc: N + に反して", max_length=500
            ),
        ),
        migrations.AddField(
            model_name="grammarpoint",
            name="meaning_vi",
            field=models.CharField(
                blank=True, help_text="Nghĩa tiếng Việt ngắn", max_length=500
            ),
        ),
        migrations.AddField(
            model_name="grammarpoint",
            name="notes",
            field=models.TextField(blank=True, help_text="Lưu ý thêm", null=True),
        ),
        migrations.AddField(
            model_name="grammarpoint",
            name="order",
            field=models.PositiveIntegerField(
                default=0, help_text="Thứ tự trong sách/level"
            ),
        ),
        migrations.AddField(
            model_name="grammarpoint",
            name="reading",
            field=models.CharField(
                blank=True, help_text="Furigana / cách đọc", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="grammarpoint",
            name="book",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="grammar_points",
                to="grammar.grammarbook",
            ),
        ),
        migrations.CreateModel(
            name="GrammarExample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sentence_jp", models.TextField(help_text="Câu tiếng Nhật")),
                ("sentence_vi", models.TextField(help_text="Dịch tiếng Việt")),
                (
                    "highlight_start",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Vị trí bắt đầu highlight (char index)",
                        null=True,
                    ),
                ),
                (
                    "highlight_end",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Vị trí kết thúc highlight (char index)",
                        null=True,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "grammar_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="structured_examples",
                        to="grammar.grammarpoint",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ví dụ ngữ pháp",
                "verbose_name_plural": "Ví dụ ngữ pháp",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="GrammarExerciseSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("N1", "N1"),
                            ("N2", "N2"),
                            ("N3", "N3"),
                            ("N4", "N4"),
                            ("N5", "N5"),
                        ],
                        default="N5",
                        max_length=2,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "question_count",
                    models.PositiveIntegerField(default=0, help_text="Tự cập nhật"),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "book",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exercise_sets",
                        to="grammar.grammarbook",
                    ),
                ),
                (
                    "grammar_point",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exercise_sets",
                        to="grammar.grammarpoint",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bộ bài tập",
                "verbose_name_plural": "Bộ bài tập",
                "ordering": ["level", "title"],
            },
        ),
        migrations.CreateModel(
            name="GrammarAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.PositiveIntegerField(default=0)),
                ("total", models.PositiveIntegerField(default=0)),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grammar_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "exercise_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="grammar.grammarexerciseset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lần làm bài",
                "verbose_name_plural": "Lần làm bài",
                "ordering": ["-completed_at"],
            },
        ),
        migrations.CreateModel(
            name="GrammarQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("MCQ", "Trắc nghiệm (MCQ)"),
                            ("SENTENCE_ORDER", "Xếp thứ tự câu (★)"),
                        ],
                        default="MCQ",
                        max_length=20,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "question_text",
                    models.TextField(
                        blank=True, help_text="Phần câu hỏi (dấu ___ cho chỗ trống)"
                    ),
                ),
                (
                    "explanation_jp",
                    models.TextField(
                        blank=True, help_text="Giải thích đáp án (tiếng Nhật)"
                    ),
                ),
                (
                    "explanation_vi",
                    models.TextField(
                        blank=True, help_text="Giải thích đáp án (tiếng Việt)"
                    ),
                ),
                (
                    "choices",
                    models.JSONField(
                        blank=True,
                        help_text='[{"key":"1","text":"〜ので"}, {"key":"2","text":"〜ながら"}, ...]',
                        null=True,
                    ),
                ),
                (
                    "correct_answer",
                    models.CharField(
                        blank=True, help_text='MCQ: "1"|"2"|"3"|"4"', max_length=50
                    ),
                ),
                (
                    "sentence_prefix",
                    models.CharField(
                        blank=True, help_text="Phần đầu câu: '彼女は'", max_length=255
                    ),
                ),
                (
                    "sentence_suffix",
                    models.CharField(
                        blank=True, help_text="Phần cuối câu: '人だ。'", max_length=255
                    ),
                ),
                (
                    "tokens",
                    models.JSONField(
                        blank=True,
                        help_text='["きれいな","とても","優しくて","そして"]',
                        null=True,
                    ),
                ),
                (
                    "correct_order",
                    models.JSONField(
                        blank=True,
                        help_text="[1,0,2,3] — index vào tokens cho box 1,2,3,4",
                        null=True,
                    ),
                ),
                (
                    "star_position",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="Box nào có ★ (1-4)", null=True
                    ),
                ),
                (
                    "exercise_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="grammar.grammarexerciseset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Câu hỏi",
                "verbose_name_plural": "Câu hỏi",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="GrammarQuestionAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_answer",
                    models.JSONField(
                        help_text="MCQ: key string; SENTENCE_ORDER: [idx,idx,idx,idx]"
                    ),
                ),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="grammar.grammarattempt",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="grammar.grammarquestion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Câu trả lời",
                "verbose_name_plural": "Câu trả lời",
            },
        ),
        migrations.CreateModel(
            name="UserGrammarProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "best_score",
                    models.PositiveIntegerField(default=0, help_text="% đúng tốt nhất"),
                ),
                (
                    "studied_at",
                    models.DateTimeField(
                        blank=True, help_text="Lần đầu xem lý thuyết", null=True
                    ),
                ),
                ("last_practiced", models.DateTimeField(blank=True, null=True)),
                (
                    "grammar_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_progress",
                        to="grammar.grammarpoint",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grammar_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tiến độ ngữ pháp",
                "verbose_name_plural": "Tiến độ ngữ pháp",
                "unique_together": {("user", "grammar_point")},
            },
        ),
    ]
