# Generated by Django 5.2.8 on 2026-03-01 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grammar', '0004_grammarbook_alter_grammarpoint_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FsrsCardStateGrammar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_data', models.JSONField(default=dict)),
                ('state', models.IntegerField(db_index=True, default=0, help_text='0=New, 1=Learning, 2=Review, 3=Relearning')),
                ('due', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_review', models.DateTimeField(blank=True, null=True)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('successful_reviews', models.PositiveIntegerField(default=0)),
                ('last_review_log', models.JSONField(blank=True, default=dict)),
                ('grammar_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fsrs_states', to='grammar.grammarpoint')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fsrs_states_grammar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'FSRS Card State (Grammar)',
                'verbose_name_plural': 'FSRS Card States (Grammar)',
                'unique_together': {('user', 'grammar_point')},
            },
        ),
    ]
