# Generated by Django 5.2.8 on 2025-11-28 11:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jp_kanji', models.CharField(blank=True, max_length=100, verbose_name='Tiếng Nhật (kanji)')),
                ('jp_kana', models.CharField(max_length=100, verbose_name='Tiếng Nhật (kana)')),
                ('romaji', models.CharField(blank=True, max_length=100, verbose_name='Romaji')),
                ('vi_meaning', models.CharField(max_length=255, verbose_name='Nghĩa tiếng Việt')),
                ('jlpt_level', models.CharField(blank=True, choices=[('N5', 'N5'), ('N4', 'N4'), ('N3', 'N3'), ('N2', 'N2'), ('N1', 'N1'), ('', 'Không rõ')], help_text='Ví dụ: N5, N4...', max_length=4, verbose_name='Cấp JLPT')),
                ('topic', models.CharField(blank=True, help_text='Ví dụ: Chào hỏi, Gia đình, Mua sắm...', max_length=100, verbose_name='Chủ đề')),
                ('example_jp', models.TextField(blank=True, verbose_name='Ví dụ tiếng Nhật')),
                ('example_vi', models.TextField(blank=True, verbose_name='Ví dụ tiếng Việt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vocab_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Từ vựng',
                'verbose_name_plural': 'Từ vựng',
                'ordering': ['jp_kana'],
            },
        ),
        migrations.CreateModel(
            name='FsrsCardState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_json', models.JSONField()),
                ('due', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_reviewed', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fsrs_cards', to=settings.AUTH_USER_MODEL)),
                ('vocab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fsrs_states', to='vocab.vocabulary')),
            ],
            options={
                'verbose_name': 'Trạng thái FSRS',
                'verbose_name_plural': 'Trạng thái FSRS',
                'unique_together': {('user', 'vocab')},
            },
        ),
    ]
