# Generated by Django 5.2.8

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStudySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_cards_per_day', models.PositiveIntegerField(default=20, help_text='Số từ mới tối đa mỗi ngày')),
                ('reviews_per_day', models.PositiveIntegerField(default=200, help_text='Số lượt ôn tập tối đa mỗi ngày')),
                ('new_cards_today', models.PositiveIntegerField(default=0)),
                ('reviews_today', models.PositiveIntegerField(default=0)),
                ('last_study_date', models.DateField(blank=True, null=True)),
                ('english_voice_preference', models.CharField(choices=[('us', 'US'), ('uk', 'UK')], default='us', help_text='Dùng để chọn audio US/UK.', max_length=2, verbose_name='Giọng tiếng Anh ưa thích (EN)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='study_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cài đặt học tập',
                'verbose_name_plural': 'Cài đặt học tập',
            },
        ),
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(db_index=True, help_text='Từ vựng (VD: record)', max_length=255, unique=True)),
                ('ipa', models.CharField(blank=True, help_text='Phiên âm (VD: /rɪˈkɔːrd/)', max_length=100)),
                ('audio_url', models.CharField(blank=True, help_text='Link file nghe (CDN link)', max_length=500)),
            ],
            options={
                'verbose_name': 'Vocabulary (Core)',
                'verbose_name_plural': 'Vocabulary (Core)',
            },
        ),
        migrations.CreateModel(
            name='WordDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meaning', models.TextField(help_text='Nghĩa tiếng Việt')),
                ('part_of_speech', models.CharField(blank=True, help_text='Từ loại (n, v, adj...)', max_length=50)),
                ('example_sentence', models.TextField(blank=True, help_text='Câu ví dụ tiếng Anh')),
                ('example_trans', models.TextField(blank=True, help_text='Dịch câu ví dụ')),
                ('image_url', models.CharField(blank=True, help_text='Ảnh minh họa', max_length=500, null=True)),
                ('vocab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='definitions', to='vocab.vocabulary')),
            ],
            options={
                'verbose_name': 'Word Definition',
                'verbose_name_plural': 'Word Definitions',
            },
        ),
        migrations.CreateModel(
            name='VocabularySet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Tên bộ (VD: TOEIC 600)', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Mô tả bộ từ vựng')),
                ('is_public', models.BooleanField(default=False, help_text='Công khai hay riêng tư')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, help_text='Null = System, ID = User', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary_sets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vocabulary Set',
                'verbose_name_plural': 'Vocabulary Sets',
            },
        ),
        migrations.CreateModel(
            name='SetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.IntegerField(default=0, help_text='Thứ tự xuất hiện')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='included_in_sets', to='vocab.worddefinition')),
                ('vocabulary_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='vocab.vocabularyset')),
            ],
            options={
                'verbose_name': 'Set Item',
                'verbose_name_plural': 'Set Items',
                'ordering': ['display_order', 'created_at'],
            },
        ),
    ]
