# Generated by Django 5.2.8 on 2025-11-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fsrscardstate',
            name='last_rating',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='fsrscardstate',
            name='successful_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fsrscardstate',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
