# Generated by Django 5.2.8 on 2026-01-22 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstudysettings',
            name='english_voice_preference',
            field=models.CharField(choices=[('us', 'US'), ('uk', 'UK')], default='us', help_text='Dùng để chọn audio US/UK. Nếu thiếu giọng ưa thích, hệ thống sẽ fallback sang giọng còn lại.', max_length=2, verbose_name='Giọng tiếng Anh ưa thích (EN)'),
        ),
    ]
