# Generated by Django 5.2.8 on 2025-11-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0002_fsrscardstate_last_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vocabulary',
            name='romaji',
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='sino_vi',
            field=models.CharField(blank=True, help_text='Ví dụ: Cát hợp, Nhân lực...', max_length=100, verbose_name='Hán tự'),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='example_vi',
            field=models.TextField(blank=True, verbose_name='Nghĩa câu ví dụ'),
        ),
    ]
