# Generated by Django 5.2.8 on 2026-01-22 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0002_alter_userstudysettings_english_voice_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabulary',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, help_text='Dữ liệu bổ sung (VD: Kanji, Romaji cho tiếng Nhật)'),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('jp', 'Japanese')], db_index=True, default='en', help_text='Ngôn ngữ của từ vựng', max_length=10),
        ),
    ]
