# Generated by Django 5.2.8 on 2026-01-22 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0003_vocabulary_extra_data_vocabulary_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabularyset',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('jp', 'Japanese')], default='en', help_text='Ngôn ngữ của bộ từ vựng', max_length=10),
        ),
        migrations.AddField(
            model_name='worddefinition',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, help_text='Dữ liệu bổ sung (VD: Furigana cho ví dụ)'),
        ),
    ]
