# Generated by Django 5.2.8 on 2025-11-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanji', '0001_initial'),
        ('vocab', '0003_remove_vocabulary_romaji_vocabulary_sino_vi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabulary',
            name='kanji_chars',
            field=models.ManyToManyField(blank=True, help_text='Các Hán tự có mặt trong từ vựng này', related_name='vocabulary_items', to='kanji.kanji'),
        ),
    ]
