# Generated by Django 5.2.8 on 2026-01-26 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0004_vocabularyset_language_worddefinition_extra_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FsrsCardStateEn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_data', models.JSONField(default=dict)),
                ('state', models.IntegerField(db_index=True, default=0, help_text='0=New, 1=Learning, 2=Review, 3=Relearning')),
                ('due', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_review', models.DateTimeField(blank=True, null=True)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('successful_reviews', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fsrs_states_en', to=settings.AUTH_USER_MODEL)),
                ('vocab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fsrs_states', to='vocab.vocabulary')),
            ],
            options={
                'verbose_name': 'FSRS Card State (EN)',
                'verbose_name_plural': 'FSRS Card States (EN)',
                'unique_together': {('user', 'vocab')},
            },
        ),
    ]
