# Generated by Django 5.2.8 on 2026-01-27 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0005_fsrscardstateen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vocabulary',
            options={'verbose_name': 'Vocabulary', 'verbose_name_plural': 'Vocabularies'},
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='audio_url',
            field=models.CharField(blank=True, help_text='[DEPRECATED] Audio URL', max_length=500),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='ipa',
            field=models.CharField(blank=True, help_text='[DEPRECATED] Phiên âm', max_length=100),
        ),
        migrations.AlterField(
            model_name='worddefinition',
            name='part_of_speech',
            field=models.CharField(blank=True, help_text='[DEPRECATED] Từ loại', max_length=50),
        ),
        migrations.AlterField(
            model_name='worddefinition',
            name='vocab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='definitions_old', to='vocab.vocabulary'),
        ),
        migrations.CreateModel(
            name='WordEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_of_speech', models.CharField(help_text='noun, verb, adj...', max_length=50)),
                ('ipa', models.CharField(blank=True, help_text='Phiên âm (VD: /ˈrek.ɚd/)', max_length=100)),
                ('audio_us', models.CharField(blank=True, help_text='Audio URL (US)', max_length=500)),
                ('audio_uk', models.CharField(blank=True, help_text='Audio URL (UK)', max_length=500)),
                ('vocab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='vocab.vocabulary')),
            ],
            options={
                'verbose_name': 'Word Entry',
                'verbose_name_plural': 'Word Entries',
                'unique_together': {('vocab', 'part_of_speech')},
            },
        ),
        migrations.AddField(
            model_name='worddefinition',
            name='entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='definitions', to='vocab.wordentry'),
        ),
    ]
