# Generated by Django 5.2.8 on 2026-01-27 12:27

from django.db import migrations


def migrate_to_three_tier(apps, schema_editor):
    """
    Migrate data from 2-tier to 3-tier structure:
    1. For each WordDefinition with vocab (old FK), create a WordEntry
    2. Link the WordDefinition to the new WordEntry
    3. Copy IPA and audio_url from Vocabulary to WordEntry
    """
    Vocabulary = apps.get_model('vocab', 'Vocabulary')
    WordEntry = apps.get_model('vocab', 'WordEntry')
    WordDefinition = apps.get_model('vocab', 'WordDefinition')
    
    # Get all definitions that still have vocab (old FK) but no entry (new FK)
    definitions = WordDefinition.objects.filter(vocab__isnull=False, entry__isnull=True)
    
    entries_created = 0
    definitions_updated = 0
    
    for definition in definitions:
        vocab = definition.vocab
        pos = definition.part_of_speech or 'unknown'
        
        # Get or create WordEntry for this (vocab, part_of_speech) combination
        entry, created = WordEntry.objects.get_or_create(
            vocab=vocab,
            part_of_speech=pos,
            defaults={
                'ipa': vocab.ipa or '',
                'audio_us': vocab.audio_url or '',  # Old audio_url becomes audio_us
                'audio_uk': ''
            }
        )
        
        if created:
            entries_created += 1
        
        # Link the definition to the new entry
        definition.entry = entry
        definition.save()
        definitions_updated += 1
    
    print(f"Created {entries_created} WordEntry records")
    print(f"Updated {definitions_updated} WordDefinition records")


def reverse_migrate(apps, schema_editor):
    """
    Reverse the migration: copy data back from WordEntry to Vocabulary/WordDefinition
    """
    WordDefinition = apps.get_model('vocab', 'WordDefinition')
    
    # Get all definitions with entry but no vocab
    definitions = WordDefinition.objects.filter(entry__isnull=False)
    
    for definition in definitions:
        if definition.entry:
            definition.vocab = definition.entry.vocab
            definition.part_of_speech = definition.entry.part_of_speech
            definition.save()


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0006_step1_add_wordentry'),
    ]

    operations = [
        migrations.RunPython(migrate_to_three_tier, reverse_migrate),
    ]

