# Generated by Django 5.2.8 on 2026-01-27 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0007_step2_migrate_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vocabulary',
            name='audio_url',
        ),
        migrations.RemoveField(
            model_name='vocabulary',
            name='ipa',
        ),
        migrations.RemoveField(
            model_name='worddefinition',
            name='part_of_speech',
        ),
        migrations.RemoveField(
            model_name='worddefinition',
            name='vocab',
        ),
        migrations.AlterField(
            model_name='worddefinition',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='definitions', to='vocab.wordentry'),
        ),
    ]
