# Generated by Django 5.2.8 on 2026-01-28 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vocab", "0008_remove_deprecated_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSetProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                ("words_learned", models.PositiveIntegerField(default=0)),
                ("words_total", models.PositiveIntegerField(default=0)),
                (
                    "quiz_best_score",
                    models.PositiveIntegerField(
                        default=0, help_text="Best quiz score as percentage (0-100)"
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "User Set Progress",
                "verbose_name_plural": "User Set Progress",
            },
        ),
        migrations.AddField(
            model_name="vocabularyset",
            name="set_number",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Set number within a TOEIC level (1-based)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="vocabularyset",
            name="toeic_level",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (600, "TOEIC 600"),
                    (730, "TOEIC 730"),
                    (860, "TOEIC 860"),
                    (990, "TOEIC 990"),
                ],
                db_index=True,
                help_text="TOEIC level (600/730/860/990). Null = not a TOEIC set.",
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="vocabularyset",
            constraint=models.UniqueConstraint(
                condition=models.Q(("toeic_level__isnull", False)),
                fields=("toeic_level", "set_number"),
                name="unique_toeic_level_set_number",
            ),
        ),
        migrations.AddField(
            model_name="usersetprogress",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="set_progress",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="usersetprogress",
            name="vocabulary_set",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_progress",
                to="vocab.vocabularyset",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="usersetprogress",
            unique_together={("user", "vocabulary_set")},
        ),
    ]
