# Generated by Django 5.2.8 on 2026-01-29 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0009_usersetprogress_vocabularyset_set_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabularyset',
            name='chapter',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='Chapter number (1-4 for Level 600)', null=True),
        ),
        migrations.AddField(
            model_name='vocabularyset',
            name='chapter_name',
            field=models.CharField(blank=True, help_text="Chapter name (VD: 'Nền tảng cốt lõi')", max_length=100),
        ),
        migrations.AddField(
            model_name='vocabularyset',
            name='milestone',
            field=models.CharField(blank=True, db_index=True, help_text="Milestone code (VD: '1A', '1B', '2A')", max_length=10),
        ),
        migrations.AddField(
            model_name='vocabularyset',
            name='priority_range',
            field=models.CharField(blank=True, help_text="Priority range (VD: '1-10', '11-20')", max_length=20),
        ),
    ]
