# Generated by Django 5.2.8 on 2026-01-29 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0010_add_chapter_milestone_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('toeic_level', models.IntegerField(blank=True, null=True, unique=True)),
                ('icon', models.TextField(blank=True, help_text='SVG Icon or Emoji')),
                ('gradient', models.CharField(default='linear-gradient(135deg, #f59e0b 0%, #d97706 100%)', help_text='CSS Gradient value', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
    ]
