# Generated by Django 5.2.8 on 2026-02-10 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vocab", "0011_course"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExampleSentence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sentence", models.TextField(help_text="Câu ví dụ tiếng Anh")),
                (
                    "translation",
                    models.TextField(blank=True, help_text="Dịch câu ví dụ"),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("cambridge", "Cambridge"),
                            ("toeic_600", "TOEIC 600"),
                            ("toeic_730", "TOEIC 730"),
                            ("toeic_860", "TOEIC 860"),
                            ("toeic_990", "TOEIC 990"),
                            ("oxford", "Oxford"),
                            ("user", "User"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="cambridge",
                        max_length=20,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="examples",
                        to="vocab.worddefinition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Example Sentence",
                "verbose_name_plural": "Example Sentences",
                "ordering": ["order", "created_at"],
            },
        ),
    ]
