# Generated by Django 5.2.8 on 2025-12-26 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('vocab', '0011_englishvocabularyexample'),
    ]

    operations = [
        migrations.AddField(
            model_name='englishvocabulary',
            name='course_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='en_vocab_items', to='core.course'),
        ),
        migrations.AddField(
            model_name='englishvocabulary',
            name='lesson_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='en_vocab_items', to='core.lesson'),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jp_vocab_items', to='core.course'),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jp_vocab_items', to='core.lesson'),
        ),
    ]
