# Generated by Django 5.2.8 on 2026-02-10 14:27

from django.db import migrations


def copy_examples_forward(apps, schema_editor):
    """Copy example_sentence/example_trans from WordDefinition to ExampleSentence."""
    WordDefinition = apps.get_model('vocab', 'WordDefinition')
    ExampleSentence = apps.get_model('vocab', 'ExampleSentence')

    definitions = WordDefinition.objects.exclude(example_sentence='').exclude(example_sentence__isnull=True)
    total = definitions.count()

    batch = []
    for defn in definitions.iterator(chunk_size=500):
        batch.append(ExampleSentence(
            definition=defn,
            sentence=defn.example_sentence,
            translation=defn.example_trans or '',
            source='cambridge',
            order=0,
        ))
        if len(batch) >= 500:
            ExampleSentence.objects.bulk_create(batch)
            batch = []

    if batch:
        ExampleSentence.objects.bulk_create(batch)

    print(f"  Migrated {total} example sentences to ExampleSentence table.")


def copy_examples_reverse(apps, schema_editor):
    """Reverse: copy ExampleSentence back to WordDefinition fields."""
    WordDefinition = apps.get_model('vocab', 'WordDefinition')
    ExampleSentence = apps.get_model('vocab', 'ExampleSentence')

    for ex in ExampleSentence.objects.select_related('definition').iterator(chunk_size=500):
        defn = ex.definition
        if not defn.example_sentence:
            defn.example_sentence = ex.sentence
            defn.example_trans = ex.translation
            defn.save(update_fields=['example_sentence', 'example_trans'])


class Migration(migrations.Migration):

    dependencies = [
        ("vocab", "0012_add_examplesentence"),
    ]

    operations = [
        migrations.RunPython(copy_examples_forward, copy_examples_reverse),
    ]
