# Generated by Django 5.2.8 on 2025-12-27 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_lesson_options_section_and_more'),
        ('vocab', '0012_englishvocabulary_course_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='englishvocabulary',
            name='section',
            field=models.CharField(blank=True, max_length=100, verbose_name='Section/Part'),
        ),
        migrations.AddField(
            model_name='englishvocabulary',
            name='section_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='en_vocab_items', to='core.section'),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jp_vocab_items', to='core.section'),
        ),
    ]
