# Generated by Django 5.2.8 on 2026-02-10 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vocab", "0013_migrate_examples_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="worddefinition",
            name="example_sentence",
        ),
        migrations.RemoveField(
            model_name="worddefinition",
            name="example_trans",
        ),
    ]
