# Generated by Django 5.2.8 on 2025-12-27 07:05

import vocab.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0013_englishvocabulary_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='englishvocabulary',
            name='audio_uk',
            field=models.FileField(blank=True, help_text='File phát âm giọng UK (mp3/wav...).', null=True, upload_to=vocab.models.en_vocab_audio_uk_upload_to, verbose_name='Audio (UK)'),
        ),
        migrations.AddField(
            model_name='englishvocabulary',
            name='audio_us',
            field=models.FileField(blank=True, help_text='File phát âm giọng US (mp3/wav...).', null=True, upload_to=vocab.models.en_vocab_audio_us_upload_to, verbose_name='Audio (US)'),
        ),
        migrations.AddField(
            model_name='englishvocabulary',
            name='image',
            field=models.ImageField(blank=True, help_text='Ảnh minh hoạ cho từ vựng (upload lên Azure).', null=True, upload_to=vocab.models.en_vocab_image_upload_to, verbose_name='Ảnh minh hoạ'),
        ),
        migrations.AddField(
            model_name='englishvocabularyexample',
            name='audio_uk',
            field=models.FileField(blank=True, help_text='Audio cho câu ví dụ giọng UK (optional).', null=True, upload_to=vocab.models.en_example_audio_uk_upload_to, verbose_name='Audio ví dụ (UK)'),
        ),
        migrations.AddField(
            model_name='englishvocabularyexample',
            name='audio_us',
            field=models.FileField(blank=True, help_text='Audio cho câu ví dụ giọng US (optional).', null=True, upload_to=vocab.models.en_example_audio_us_upload_to, verbose_name='Audio ví dụ (US)'),
        ),
        migrations.AddField(
            model_name='userstudysettings',
            name='english_voice_preference',
            field=models.CharField(choices=[('us', 'US'), ('uk', 'UK')], default='us', help_text='Dùng để chọn audio US/UK (từ vựng + ví dụ). Nếu thiếu giọng ưa thích, hệ thống sẽ fallback sang giọng còn lại.', max_length=2, verbose_name='Giọng tiếng Anh ưa thích (EN)'),
        ),
    ]
