# Generated by Django 5.2.8 on 2026-02-10 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vocab", "0014_remove_old_example_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="SetItemExample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "example",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="set_item_links",
                        to="vocab.examplesentence",
                    ),
                ),
                (
                    "set_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="set_examples",
                        to="vocab.setitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Set Item Example",
                "verbose_name_plural": "Set Item Examples",
                "ordering": ["order"],
                "unique_together": {("set_item", "example")},
            },
        ),
    ]
