# Generated by Django 5.2.8 on 2026-02-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0016_course_language_mimikara'),
    ]

    operations = [
        migrations.CreateModel(
            name='VocabSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Mã nguồn (VD: mimikara_n2, toeic_600)', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Tên hiển thị (VD: Mimikara N2, TOEIC 600)', max_length=200)),
                ('source_type', models.CharField(choices=[('book', 'Sách'), ('course', 'Khóa học'), ('topic', 'Chủ đề'), ('exam', 'Đề thi'), ('dictionary', 'Từ điển'), ('user', 'Người dùng'), ('other', 'Khác')], default='book', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Mô tả chi tiết')),
                ('language', models.CharField(blank=True, help_text='Ngôn ngữ chính (en, jp, etc.)', max_length=10)),
                ('level', models.CharField(blank=True, help_text='Cấp độ (N2, B2, 600, etc.)', max_length=50)),
                ('publisher', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vocab Source',
                'verbose_name_plural': 'Vocab Sources',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='examplesentence',
            name='source',
            field=models.CharField(choices=[('cambridge', 'Cambridge'), ('toeic_600', 'TOEIC 600'), ('toeic_730', 'TOEIC 730'), ('toeic_860', 'TOEIC 860'), ('toeic_990', 'TOEIC 990'), ('mimikara_n2', 'Mimikara N2'), ('oxford', 'Oxford'), ('user', 'User'), ('other', 'Other')], db_index=True, default='cambridge', max_length=20),
        ),
    ]
