# Generated by Django 5.2.8 on 2026-02-14 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0017_add_vocabsource_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabularyset',
            name='collection',
            field=models.ForeignKey(blank=True, help_text='Bộ từ vựng chứa set này (VD: Mimikara N2, Minna N5)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sets', to='vocab.vocabsource'),
        ),
        migrations.AlterField(
            model_name='vocabularyset',
            name='description',
            field=models.TextField(blank=True, help_text='Mô tả set từ vựng'),
        ),
        migrations.AlterField(
            model_name='vocabularyset',
            name='title',
            field=models.CharField(help_text='Tên set (VD: Bài 1 - Động từ)', max_length=255),
        ),
    ]
