# Generated by Django 5.2.8 on 2026-02-14 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0018_add_collection_to_vocabularyset'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='collection',
            field=models.OneToOneField(blank=True, help_text='Liên kết với bộ từ vựng (VocabSource)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course', to='vocab.vocabsource'),
        ),
    ]
