# Generated by Django 5.2.8 on 2026-02-15 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0019_add_collection_to_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examplesentence',
            name='source',
            field=models.CharField(choices=[('cambridge', 'Cambridge'), ('toeic_600', 'TOEIC 600'), ('toeic_730', 'TOEIC 730'), ('toeic_860', 'TOEIC 860'), ('toeic_990', 'TOEIC 990'), ('mimikara_n2', 'Mimikara N2'), ('oxford', 'Oxford'), ('user', 'User'), ('other', 'Other')], db_index=True, default='cambridge', max_length=50),
        ),
    ]
