# Generated by Django 5.2.8 on 2026-02-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0020_increase_source_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabsource',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Ảnh bìa cho bộ từ vựng (600×330px recommended)', null=True, upload_to='vocab_sources/'),
        ),
    ]
