# Generated by Django 5.2.8 on 2026-02-16 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vocab", "0021_add_cover_image_to_vocabsource"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuizQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("meaning", "Meaning"),
                            ("reading", "Reading"),
                            ("kanji", "Kanji"),
                        ],
                        max_length=10,
                    ),
                ),
                ("correct_answer", models.CharField(max_length=255)),
                ("distractors", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "set_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_questions",
                        to="vocab.setitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quiz Question",
                "verbose_name_plural": "Quiz Questions",
                "unique_together": {("set_item", "question_type")},
            },
        ),
    ]
