# Generated by Django 5.2.8 on 2026-02-16 05:14

import re
from django.db import migrations


def fix_readings(apps, schema_editor):
    """
    Fix JP vocabulary readings that only contain furigana portions.
    E.g. 知り合い had reading=しあ instead of しりあい.
    Derives correct full reading from html_display ruby tags.
    """
    Vocabulary = apps.get_model("vocab", "Vocabulary")
    fixed = 0
    for v in Vocabulary.objects.filter(language="jp").exclude(extra_data={}):
        ed = v.extra_data or {}
        html = ed.get("html_display", "")
        reading = ed.get("reading", "")
        if not html or "<ruby>" not in html:
            continue
        full_reading = re.sub(r"<ruby>[^<]*<rt>([^<]*)</rt></ruby>", r"\1", html)
        full_reading = re.sub(r"<[^>]+>", "", full_reading)
        if full_reading and full_reading != reading and len(full_reading) >= len(reading):
            v.extra_data["reading"] = full_reading
            v.save(update_fields=["extra_data"])
            fixed += 1


class Migration(migrations.Migration):

    dependencies = [
        ("vocab", "0022_quizquestion"),
    ]

    operations = [
        migrations.RunPython(fix_readings, migrations.RunPython.noop),
    ]
