# Generated by Django 5.2.8 on 2026-02-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0023_fix_jp_reading_from_html_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='mondai_type',
            field=models.CharField(blank=True, help_text='Tag for JLPT mondai type', max_length=50, null=True),
        ),
    ]
