# Generated by Django 5.2.8 on 2026-02-25 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0024_quizquestion_mondai_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordentry',
            name='part_of_speech',
            field=models.CharField(blank=True, default='', help_text='noun, verb, adj...', max_length=50),
        ),
    ]
