# Generated by Django 5.2.8 on 2026-02-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0025_part_of_speech_blank_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='fsrscardstateen',
            name='last_review_log',
            field=models.JSONField(blank=True, default=dict, help_text='Last FSRS review log (rating, elapsed_days, scheduled_days, etc.)'),
        ),
    ]
