# Generated by Django 5.2.8 on 2026-01-15 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('unique_visitors', models.PositiveIntegerField(default=0)),
                ('unique_users', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Daily stats',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PopularPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('path', models.CharField(max_length=500)),
                ('views', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-date', '-views'],
                'unique_together': {('date', 'path')},
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_index=True, max_length=500)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('referer', models.URLField(blank=True, default='', max_length=1000)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('browser', models.CharField(blank=True, default='', max_length=100)),
                ('device', models.CharField(blank=True, default='', max_length=100)),
                ('os', models.CharField(blank=True, default='', max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['path', 'timestamp'], name='analytics_p_path_51c7b7_idx'), models.Index(fields=['timestamp'], name='analytics_p_timesta_835321_idx')],
            },
        ),
    ]
