include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_single_quotes
    - sort_child_properties_last
    - use_build_context_synchronously
    - avoid_print: false
