# Generated by Django 5.2.8 on 2026-01-04 11:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tên gói (VD: Premium 1 tháng)', max_length=100)),
                ('slug', models.SlugField(help_text='Slug cho URL', unique=True)),
                ('description', models.TextField(blank=True, help_text='Mô tả gói')),
                ('price', models.DecimalField(decimal_places=0, help_text='Giá tiền (VND)', max_digits=12)),
                ('duration_days', models.PositiveIntegerField(help_text='Số ngày hiệu lực')),
                ('features', models.JSONField(blank=True, default=list, help_text='Danh sách tính năng (JSON array)')),
                ('is_active', models.BooleanField(default=True)),
                ('is_popular', models.BooleanField(default=False, help_text='Đánh dấu gói phổ biến')),
                ('order', models.PositiveIntegerField(default=0, help_text='Thứ tự hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gói thanh toán',
                'verbose_name_plural': 'Gói thanh toán',
                'ordering': ['order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='payment.paymentplan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gói đăng ký',
                'verbose_name_plural': 'Gói đăng ký',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=0, help_text='Số tiền (VND)', max_digits=12)),
                ('payment_method', models.CharField(choices=[('bank', 'Chuyển khoản ngân hàng')], default='bank', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Chờ thanh toán'), ('processing', 'Đang xử lý'), ('completed', 'Đã thanh toán'), ('failed', 'Thất bại'), ('cancelled', 'Đã hủy')], default='pending', max_length=20)),
                ('bank_account_name', models.CharField(blank=True, help_text='Tên chủ tài khoản', max_length=200)),
                ('bank_account_number', models.CharField(blank=True, help_text='Số tài khoản', max_length=50)),
                ('bank_name', models.CharField(blank=True, help_text='Tên ngân hàng', max_length=100)),
                ('bank_transfer_code', models.CharField(blank=True, help_text='Mã giao dịch chuyển khoản', max_length=100)),
                ('bank_transfer_image', models.ImageField(blank=True, help_text='Ảnh chụp biên lai chuyển khoản', null=True, upload_to='payments/bank_transfers/')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Thông tin bổ sung (JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payment.paymentplan')),
            ],
            options={
                'verbose_name': 'Giao dịch thanh toán',
                'verbose_name_plural': 'Giao dịch thanh toán',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='payment_pay_user_id_2df5ec_idx'), models.Index(fields=['status'], name='payment_pay_status_124d3d_idx'), models.Index(fields=['bank_transfer_code'], name='payment_pay_bank_tr_6c477a_idx')],
            },
        ),
    ]
