# Generated by Django 5.2.8 on 2026-03-03 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_type', models.CharField(db_index=True, max_length=50)),
                ('quiz_id', models.CharField(db_index=True, max_length=100)),
                ('total_questions', models.PositiveIntegerField()),
                ('correct_count', models.PositiveIntegerField()),
                ('score', models.FloatField(help_text='0.0 - 10.0')),
                ('answers_detail', models.JSONField(blank=True, default=list)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quiz Result',
                'verbose_name_plural': 'Quiz Results',
                'ordering': ['-completed_at'],
                'indexes': [models.Index(fields=['user', 'quiz_type', 'quiz_id'], name='common_quiz_user_id_071dd9_idx')],
            },
        ),
    ]
