# Generated by Django 5.2.8 on 2026-01-14 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Tiêu đề ngắn gọn cho đề xuất', max_length=200, verbose_name='Tiêu đề')),
                ('description', models.TextField(help_text='Mô tả chi tiết về đề xuất hoặc lỗi', verbose_name='Mô tả chi tiết')),
                ('type', models.CharField(choices=[('feature', 'Feature Request'), ('bug', 'Bug Report')], default='feature', max_length=20, verbose_name='Loại')),
                ('status', models.CharField(choices=[('new', 'Mới'), ('planned', 'Đã lên kế hoạch'), ('in_progress', 'Đang làm'), ('done', 'Đã xong')], default='new', max_length=20, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('upvotes', models.ManyToManyField(blank=True, related_name='upvoted_feedback', to=settings.AUTH_USER_MODEL, verbose_name='Lượt vote')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_items', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
            ],
            options={
                'verbose_name': 'Đề xuất',
                'verbose_name_plural': 'Đề xuất',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Nội dung bình luận', verbose_name='Nội dung')),
                ('is_admin_response', models.BooleanField(default=False, help_text='Đánh dấu nếu đây là phản hồi chính thức từ Admin', verbose_name='Phản hồi chính thức')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_comments', to=settings.AUTH_USER_MODEL, verbose_name='Người bình luận')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='feedback.feedbackitem', verbose_name='Đề xuất')),
            ],
            options={
                'verbose_name': 'Bình luận',
                'verbose_name_plural': 'Bình luận',
                'ordering': ['created_at'],
            },
        ),
    ]
