# Generated by Django 5.2.8 on 2025-11-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kanji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char', models.CharField(max_length=1, unique=True, verbose_name='Hán tự')),
                ('sino_vi', models.CharField(blank=True, max_length=50, verbose_name='Âm Hán Việt')),
                ('keyword', models.CharField(blank=True, help_text='Ví dụ: Accept, Control, Dawn ...', max_length=100, verbose_name='Keyword')),
                ('onyomi', models.CharField(blank=True, max_length=100, verbose_name='Âm on')),
                ('kunyomi', models.CharField(blank=True, max_length=100, verbose_name='Âm kun')),
                ('level', models.PositiveIntegerField(default=1, verbose_name='Level')),
                ('jlpt_level', models.CharField(blank=True, max_length=4, verbose_name='JLPT')),
                ('strokes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Số nét')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú / câu chuyện nhớ')),
            ],
            options={
                'verbose_name': 'Hán tự đơn',
                'verbose_name_plural': 'Hán tự đơn',
                'ordering': ['level', 'char'],
            },
        ),
    ]
