# Generated by Django 5.2.8 on 2026-02-22 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kanji", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserKanjiProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("learning", "Đang học"), ("mastered", "Đã thuộc")],
                        default="learning",
                        max_length=20,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "correct_streak",
                    models.PositiveIntegerField(default=0, verbose_name="Chuỗi đúng"),
                ),
                (
                    "last_practiced",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Lần cuối luyện"
                    ),
                ),
                (
                    "kanji",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_progress",
                        to="kanji.kanji",
                        verbose_name="Hán tự",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kanji_progress",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người dùng",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tiến trình học Hán tự",
                "verbose_name_plural": "Tiến trình học Hán tự",
                "ordering": ["-last_practiced"],
                "unique_together": {("user", "kanji")},
            },
        ),
    ]
