# Generated by Django 5.2.8 on 2026-02-24 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kanji", "0002_add_user_kanji_progress"),
        ("vocab", "0024_quizquestion_mondai_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="kanji",
            options={
                "ordering": ["lesson", "order", "char"],
                "verbose_name": "Hán tự",
                "verbose_name_plural": "Hán tự",
            },
        ),
        migrations.RemoveField(
            model_name="kanji",
            name="jlpt_level",
        ),
        migrations.RemoveField(
            model_name="kanji",
            name="level",
        ),
        migrations.AddField(
            model_name="kanji",
            name="order",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Thứ tự trong bài"
            ),
        ),
        migrations.AlterField(
            model_name="kanji",
            name="keyword",
            field=models.CharField(
                blank=True,
                help_text="Từ khóa để nhớ nghĩa, vd: Sun, Moon, Gold …",
                max_length=100,
                verbose_name="Keyword",
            ),
        ),
        migrations.CreateModel(
            name="KanjiLesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "jlpt_level",
                    models.CharField(
                        choices=[
                            ("N5", "N5"),
                            ("N4", "N4"),
                            ("N3", "N3"),
                            ("N2", "N2"),
                            ("N1", "N1"),
                        ],
                        default="N5",
                        max_length=2,
                        verbose_name="Cấp JLPT",
                    ),
                ),
                ("lesson_number", models.PositiveIntegerField(verbose_name="Số bài")),
                (
                    "topic",
                    models.CharField(max_length=200, verbose_name="Chủ đề bài học"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Thứ tự hiển thị"
                    ),
                ),
            ],
            options={
                "verbose_name": "Bài học Kanji",
                "verbose_name_plural": "Bài học Kanji",
                "ordering": ["jlpt_level", "order", "lesson_number"],
                "unique_together": {("jlpt_level", "lesson_number")},
            },
        ),
        migrations.AddField(
            model_name="kanji",
            name="lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="kanjis",
                to="kanji.kanjilesson",
                verbose_name="Bài học",
            ),
        ),
        migrations.CreateModel(
            name="KanjiVocab",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=100, verbose_name="Từ vựng")),
                (
                    "reading",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Cách đọc (hiragana)"
                    ),
                ),
                (
                    "meaning",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Nghĩa tiếng Việt"
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Số nhỏ hơn hiển thị trước (0 = ưu tiên cao nhất)",
                        verbose_name="Ưu tiên",
                    ),
                ),
                (
                    "kanji",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vocab_examples",
                        to="kanji.kanji",
                        verbose_name="Hán tự",
                    ),
                ),
                (
                    "vocabulary",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kanji_vocab_examples",
                        to="vocab.vocabulary",
                        verbose_name="Liên kết Vocabulary",
                    ),
                ),
            ],
            options={
                "verbose_name": "Từ vựng mẫu Kanji",
                "verbose_name_plural": "Từ vựng mẫu Kanji",
                "ordering": ["priority", "id"],
                "unique_together": {("kanji", "word")},
            },
        ),
    ]
