# Generated by Django 5.2.8 on 2026-02-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kanji", "0003_kanji_lesson_vocab"),
    ]

    operations = [
        migrations.AddField(
            model_name="kanji",
            name="meaning_vi",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Nghĩa tiếng Việt"
            ),
        ),
    ]
