# Generated by Django 5.2.8 on 2026-02-26 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanji', '0004_add_meaning_vi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kanjilesson',
            name='jlpt_level',
            field=models.CharField(choices=[('N5', 'N5'), ('N4', 'N4'), ('N3', 'N3'), ('N2', 'N2'), ('N1', 'N1'), ('BT', '214 Bộ thủ')], default='N5', max_length=3, verbose_name='Cấp JLPT'),
        ),
    ]
