# Generated by Django 5.2.8 on 2026-02-26 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanji', '0005_add_bt_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanji',
            name='formation',
            field=models.CharField(blank=True, help_text='VD: Hình thanh: 糸(ý: sợi chỉ) + 泉(âm: セン) → tuyến, dây', max_length=300, verbose_name='Phương pháp hình thành'),
        ),
    ]
