# Generated by Django 5.2.8 on 2026-02-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanji', '0006_add_formation_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kanji',
            name='formation',
            field=models.CharField(blank=True, help_text='VD: Hình thanh: 糸(ý: sợi chỉ) + 泉(âm: セン) → tuyến, dây', max_length=500, verbose_name='Phương pháp hình thành'),
        ),
    ]
