# Generated by Django 5.2.8 on 2026-02-27 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanji', '0007_formation_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='KanjiQuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('meaning', 'Nghĩa'), ('reading', 'Cách đọc'), ('kanji', 'Hán tự')], max_length=10, verbose_name='Loại câu hỏi')),
                ('correct_answer', models.CharField(max_length=255, verbose_name='Đáp án đúng')),
                ('distractors', models.JSONField(default=list, help_text='["wrong1", "wrong2", "wrong3"]', verbose_name='Đáp án nhiễu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kanji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='kanji.kanji', verbose_name='Hán tự')),
            ],
            options={
                'verbose_name': 'Câu hỏi Quiz Kanji',
                'verbose_name_plural': 'Câu hỏi Quiz Kanji',
                'unique_together': {('kanji', 'question_type')},
            },
        ),
    ]
