# Generated by Django 5.2.8 on 2026-02-27 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanji', '0008_kanjiquizquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanjivocab',
            name='jlpt_level',
            field=models.CharField(blank=True, default='', help_text='N5, N4, N3, N2, N1', max_length=5, verbose_name='Cấp JLPT'),
        ),
    ]
