# Generated by Django 5.2.8 on 2026-03-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanji', '0009_kanjivocab_jlpt_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kanji',
            name='char',
            field=models.CharField(max_length=10, unique=True, verbose_name='Hán tự'),
        ),
    ]
