# Generated by Django 5.2.8 on 2026-01-30 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvatarFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.PositiveIntegerField(default=100)),
                ('rarity', models.CharField(choices=[('COMMON', 'Thường'), ('RARE', 'Hiếm'), ('EPIC', 'Sử thi'), ('LEGENDARY', 'Huyền thoại')], default='COMMON', max_length=20)),
                ('css_gradient', models.CharField(default='linear-gradient(135deg, #667eea 0%, #764ba2 100%)', help_text='CSS gradient cho viền khung', max_length=500)),
                ('css_animation', models.CharField(blank=True, help_text='Tên CSS animation (vd: pulse, glow, rainbow)', max_length=200)),
                ('border_width', models.PositiveIntegerField(default=3)),
                ('preview_image', models.ImageField(blank=True, help_text='Ảnh preview của khung', null=True, upload_to='shop/frames/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_limited', models.BooleanField(default=False, help_text='Sản phẩm giới hạn thời gian')),
                ('available_until', models.DateTimeField(blank=True, help_text='Chỉ hiển thị nếu is_limited=True', null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Khung Avatar',
                'verbose_name_plural': 'Khung Avatar',
                'ordering': ['display_order', 'rarity', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('is_equipped', models.BooleanField(default=False)),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='shop.avatarframe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inventory Item',
                'verbose_name_plural': 'Inventory Items',
                'unique_together': {('user', 'frame')},
            },
        ),
    ]
