# Generated by Django 5.2.8 on 2026-01-14 18:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CoinTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.IntegerField(
                        help_text="Số coin thay đổi. Dương = nhận, Âm = trừ"
                    ),
                ),
                (
                    "balance_after",
                    models.PositiveIntegerField(
                        help_text="Số dư sau khi giao dịch hoàn tất"
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("CHECK_IN", "Điểm danh hàng ngày"),
                            ("PURCHASE", "Mua hàng"),
                            ("BONUS", "Thưởng"),
                            ("REFUND", "Hoàn tiền"),
                            ("ADMIN_ADJUST", "Admin điều chỉnh"),
                            ("STREAK_BONUS", "Thưởng chuỗi điểm danh"),
                            ("GIFT", "Quà tặng"),
                            ("EVENT", "Sự kiện"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Mô tả chi tiết về giao dịch"
                    ),
                ),
                (
                    "reference_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID tham chiếu (order_id, payment_id, etc.)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coin_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Giao dịch coin",
                "verbose_name_plural": "Giao dịch coin",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="wallet_coin_user_id_8feb4f_idx",
                    ),
                    models.Index(
                        fields=["transaction_type"],
                        name="wallet_coin_transac_f44bc5_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="wallet_coin_created_d243eb_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserWallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "coins",
                    models.PositiveIntegerField(default=0, help_text="Số coin hiện có"),
                ),
                (
                    "last_checkin_date",
                    models.DateField(
                        blank=True, help_text="Ngày điểm danh cuối cùng", null=True
                    ),
                ),
                (
                    "checkin_streak",
                    models.PositiveIntegerField(
                        default=0, help_text="Số ngày điểm danh liên tục"
                    ),
                ),
                (
                    "is_locked",
                    models.BooleanField(
                        default=False,
                        help_text="Ví có bị khóa không (do vi phạm, etc.)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ví tiền",
                "verbose_name_plural": "Ví tiền",
                "indexes": [
                    models.Index(fields=["user"], name="wallet_user_user_id_52b91e_idx")
                ],
            },
        ),
    ]
