# Generated by Django 5.2.8 on 2026-02-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="Tên sách")),
                (
                    "author",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="Tác giả"
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="ebook/covers/",
                        verbose_name="Ảnh bìa",
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(upload_to="ebook/pdfs/", verbose_name="File PDF"),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="Mô tả"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
            ],
            options={
                "verbose_name": "Ebook",
                "verbose_name_plural": "Ebooks",
                "ordering": ["-created_at"],
            },
        ),
    ]
