# Generated by Django 5.2.8 on 2025-11-29 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcriptline',
            name='start_time',
            field=models.PositiveIntegerField(help_text='Thời gian bắt đầu (giây) từ đầu video'),
        ),
    ]
