"""214 Kangxi Radicals data - Part 2: 6-stroke to 17-stroke (radicals 95-214)"""

RADICALS_6 = [
  {"character":"竹","han_viet":"Trúc","onyomi":["チク"],"kunyomi":["たけ"],"meaning_vi":"Tre"},
  {"character":"米","han_viet":"Mễ","onyomi":["ベイ"],"kunyomi":["こめ"],"meaning_vi":"Gạo"},
  {"character":"糸","han_viet":"Mịch","onyomi":["シ"],"kunyomi":["いと"],"meaning_vi":"Sợi tơ"},
  {"character":"缶","han_viet":"Phữu","onyomi":["カン"],"kunyomi":[],"meaning_vi":"Cái vại"},
  {"character":"网","han_viet":"Võng","onyomi":["モウ"],"kunyomi":[],"meaning_vi":"Lưới"},
  {"character":"羊","han_viet":"Dương","onyomi":["ヨウ"],"kunyomi":["ひつじ"],"meaning_vi":"Con dê"},
  {"character":"羽","han_viet":"Vũ","onyomi":["ウ"],"kunyomi":["はね"],"meaning_vi":"Lông vũ"},
  {"character":"老","han_viet":"Lão","onyomi":["ロウ"],"kunyomi":["お-いる"],"meaning_vi":"Già"},
  {"character":"而","han_viet":"Nhi","onyomi":["ジ"],"kunyomi":[],"meaning_vi":"Mà, và"},
  {"character":"耒","han_viet":"Lỗi","onyomi":["ライ"],"kunyomi":[],"meaning_vi":"Cái cày"},
  {"character":"耳","han_viet":"Nhĩ","onyomi":["ジ"],"kunyomi":["みみ"],"meaning_vi":"Tai"},
  {"character":"聿","han_viet":"Duật","onyomi":["イツ"],"kunyomi":[],"meaning_vi":"Cây bút"},
  {"character":"肉","han_viet":"Nhục","onyomi":["ニク"],"kunyomi":[],"meaning_vi":"Thịt"},
  {"character":"臣","han_viet":"Thần","onyomi":["シン"],"kunyomi":[],"meaning_vi":"Bề tôi"},
  {"character":"自","han_viet":"Tự","onyomi":["ジ"],"kunyomi":["みずか-ら"],"meaning_vi":"Tự mình"},
  {"character":"至","han_viet":"Chí","onyomi":["シ"],"kunyomi":["いた-る"],"meaning_vi":"Đến"},
  {"character":"臼","han_viet":"Cữu","onyomi":["キュウ"],"kunyomi":["うす"],"meaning_vi":"Cối giã"},
  {"character":"舌","han_viet":"Thiệt","onyomi":["ゼツ"],"kunyomi":["した"],"meaning_vi":"Lưỡi"},
  {"character":"舛","han_viet":"Suyễn","onyomi":["セン"],"kunyomi":[],"meaning_vi":"Trái ngược"},
  {"character":"舟","han_viet":"Chu","onyomi":["シュウ"],"kunyomi":["ふね"],"meaning_vi":"Con thuyền"},
  {"character":"艮","han_viet":"Cấn","onyomi":["ゴン"],"kunyomi":[],"meaning_vi":"Dừng lại"},
  {"character":"色","han_viet":"Sắc","onyomi":["ショク"],"kunyomi":["いろ"],"meaning_vi":"Màu sắc"},
  {"character":"艸","han_viet":"Thảo","onyomi":["ソウ"],"kunyomi":["くさ"],"meaning_vi":"Cỏ"},
  {"character":"虍","han_viet":"Hô","onyomi":["コ"],"kunyomi":[],"meaning_vi":"Vằn hổ"},
  {"character":"虫","han_viet":"Trùng","onyomi":["チュウ"],"kunyomi":["むし"],"meaning_vi":"Con sâu"},
  {"character":"血","han_viet":"Huyết","onyomi":["ケツ"],"kunyomi":["ち"],"meaning_vi":"Máu"},
  {"character":"行","han_viet":"Hành","onyomi":["コウ"],"kunyomi":["い-く"],"meaning_vi":"Đi, hành"},
  {"character":"衣","han_viet":"Y","onyomi":["イ"],"kunyomi":["ころも"],"meaning_vi":"Áo"},
  {"character":"襾","han_viet":"Á","onyomi":["ア"],"kunyomi":[],"meaning_vi":"Che phủ"},
]

RADICALS_7 = [
  {"character":"見","han_viet":"Kiến","onyomi":["ケン"],"kunyomi":["み-る"],"meaning_vi":"Nhìn"},
  {"character":"角","han_viet":"Giác","onyomi":["カク"],"kunyomi":["つの"],"meaning_vi":"Sừng, góc"},
  {"character":"言","han_viet":"Ngôn","onyomi":["ゲン"],"kunyomi":["い-う"],"meaning_vi":"Lời nói"},
  {"character":"谷","han_viet":"Cốc","onyomi":["コク"],"kunyomi":["たに"],"meaning_vi":"Thung lũng"},
  {"character":"豆","han_viet":"Đậu","onyomi":["トウ"],"kunyomi":["まめ"],"meaning_vi":"Đậu"},
  {"character":"豕","han_viet":"Thỉ","onyomi":["シ"],"kunyomi":[],"meaning_vi":"Con lợn"},
  {"character":"豸","han_viet":"Trĩ","onyomi":["チ"],"kunyomi":[],"meaning_vi":"Thú không sừng"},
  {"character":"貝","han_viet":"Bối","onyomi":["バイ"],"kunyomi":["かい"],"meaning_vi":"Vỏ sò"},
  {"character":"赤","han_viet":"Xích","onyomi":["セキ"],"kunyomi":["あか"],"meaning_vi":"Đỏ"},
  {"character":"走","han_viet":"Tẩu","onyomi":["ソウ"],"kunyomi":["はし-る"],"meaning_vi":"Chạy"},
  {"character":"足","han_viet":"Túc","onyomi":["ソク"],"kunyomi":["あし"],"meaning_vi":"Chân"},
  {"character":"身","han_viet":"Thân","onyomi":["シン"],"kunyomi":["み"],"meaning_vi":"Thân thể"},
  {"character":"車","han_viet":"Xa","onyomi":["シャ"],"kunyomi":["くるま"],"meaning_vi":"Xe"},
  {"character":"辛","han_viet":"Tân","onyomi":["シン"],"kunyomi":["から-い"],"meaning_vi":"Cay"},
  {"character":"辰","han_viet":"Thìn","onyomi":["シン"],"kunyomi":[],"meaning_vi":"Buổi sáng"},
  {"character":"辵","han_viet":"Sước","onyomi":["チャク"],"kunyomi":[],"meaning_vi":"Đi, chạy"},
  {"character":"邑","han_viet":"Ấp","onyomi":["ユウ"],"kunyomi":[],"meaning_vi":"Ấp, làng"},
  {"character":"酉","han_viet":"Dậu","onyomi":["ユウ"],"kunyomi":[],"meaning_vi":"Rượu, Dậu"},
  {"character":"釆","han_viet":"Biện","onyomi":["ベン"],"kunyomi":[],"meaning_vi":"Phân biệt"},
  {"character":"里","han_viet":"Lý","onyomi":["リ"],"kunyomi":["さと"],"meaning_vi":"Làng, dặm"},
]

RADICALS_8 = [
  {"character":"金","han_viet":"Kim","onyomi":["キン"],"kunyomi":["かね"],"meaning_vi":"Vàng, kim loại"},
  {"character":"長","han_viet":"Trường","onyomi":["チョウ"],"kunyomi":["なが-い"],"meaning_vi":"Dài"},
  {"character":"門","han_viet":"Môn","onyomi":["モン"],"kunyomi":["かど"],"meaning_vi":"Cổng"},
  {"character":"阜","han_viet":"Phụ","onyomi":["フ"],"kunyomi":[],"meaning_vi":"Gò đất"},
  {"character":"隶","han_viet":"Đãi","onyomi":["タイ"],"kunyomi":[],"meaning_vi":"Đến kịp"},
  {"character":"隹","han_viet":"Chuy","onyomi":["スイ"],"kunyomi":[],"meaning_vi":"Chim đuôi ngắn"},
  {"character":"雨","han_viet":"Vũ","onyomi":["ウ"],"kunyomi":["あめ"],"meaning_vi":"Mưa"},
  {"character":"青","han_viet":"Thanh","onyomi":["セイ"],"kunyomi":["あお"],"meaning_vi":"Xanh"},
  {"character":"非","han_viet":"Phi","onyomi":["ヒ"],"kunyomi":[],"meaning_vi":"Không phải"},
]

RADICALS_9 = [
  {"character":"面","han_viet":"Diện","onyomi":["メン"],"kunyomi":["おも"],"meaning_vi":"Mặt"},
  {"character":"革","han_viet":"Cách","onyomi":["カク"],"kunyomi":["かわ"],"meaning_vi":"Da thuộc"},
  {"character":"韋","han_viet":"Vi","onyomi":["イ"],"kunyomi":[],"meaning_vi":"Da mềm"},
  {"character":"韭","han_viet":"Cửu","onyomi":["キュウ"],"kunyomi":["にら"],"meaning_vi":"Cây hẹ"},
  {"character":"音","han_viet":"Âm","onyomi":["オン"],"kunyomi":["おと"],"meaning_vi":"Âm thanh"},
  {"character":"頁","han_viet":"Hiệt","onyomi":["ケツ"],"kunyomi":[],"meaning_vi":"Đầu, trang"},
  {"character":"風","han_viet":"Phong","onyomi":["フウ"],"kunyomi":["かぜ"],"meaning_vi":"Gió"},
  {"character":"飛","han_viet":"Phi","onyomi":["ヒ"],"kunyomi":["と-ぶ"],"meaning_vi":"Bay"},
  {"character":"食","han_viet":"Thực","onyomi":["ショク"],"kunyomi":["た-べる"],"meaning_vi":"Ăn"},
  {"character":"首","han_viet":"Thủ","onyomi":["シュ"],"kunyomi":["くび"],"meaning_vi":"Cái đầu"},
  {"character":"香","han_viet":"Hương","onyomi":["コウ"],"kunyomi":["か"],"meaning_vi":"Thơm"},
]

RADICALS_10_17 = [
  {"character":"馬","han_viet":"Mã","onyomi":["バ"],"kunyomi":["うま"],"meaning_vi":"Ngựa"},
  {"character":"骨","han_viet":"Cốt","onyomi":["コツ"],"kunyomi":["ほね"],"meaning_vi":"Xương"},
  {"character":"高","han_viet":"Cao","onyomi":["コウ"],"kunyomi":["たか-い"],"meaning_vi":"Cao"},
  {"character":"髟","han_viet":"Bưu","onyomi":["ヒョウ"],"kunyomi":[],"meaning_vi":"Tóc dài"},
  {"character":"鬥","han_viet":"Đấu","onyomi":["トウ"],"kunyomi":[],"meaning_vi":"Đánh nhau"},
  {"character":"鬯","han_viet":"Sưởng","onyomi":["チョウ"],"kunyomi":[],"meaning_vi":"Rượu thơm"},
  {"character":"鬲","han_viet":"Cách","onyomi":["カク"],"kunyomi":[],"meaning_vi":"Nồi ba chân"},
  {"character":"鬼","han_viet":"Quỷ","onyomi":["キ"],"kunyomi":["おに"],"meaning_vi":"Ma quỷ"},
  {"character":"魚","han_viet":"Ngư","onyomi":["ギョ"],"kunyomi":["うお"],"meaning_vi":"Cá"},
  {"character":"鳥","han_viet":"Điểu","onyomi":["チョウ"],"kunyomi":["とり"],"meaning_vi":"Chim"},
  {"character":"鹵","han_viet":"Lỗ","onyomi":["ロ"],"kunyomi":[],"meaning_vi":"Muối"},
  {"character":"鹿","han_viet":"Lộc","onyomi":["ロク"],"kunyomi":["しか"],"meaning_vi":"Con hươu"},
  {"character":"麥","han_viet":"Mạch","onyomi":["バク"],"kunyomi":["むぎ"],"meaning_vi":"Lúa mạch"},
  {"character":"麻","han_viet":"Ma","onyomi":["マ"],"kunyomi":["あさ"],"meaning_vi":"Cây gai"},
  {"character":"黃","han_viet":"Hoàng","onyomi":["コウ"],"kunyomi":["き"],"meaning_vi":"Vàng"},
  {"character":"黍","han_viet":"Thử","onyomi":["ショ"],"kunyomi":["きび"],"meaning_vi":"Kê"},
  {"character":"黑","han_viet":"Hắc","onyomi":["コク"],"kunyomi":["くろ"],"meaning_vi":"Đen"},
  {"character":"黹","han_viet":"Chỉ","onyomi":["チ"],"kunyomi":[],"meaning_vi":"Thêu"},
  {"character":"黽","han_viet":"Mãnh","onyomi":["ベン"],"kunyomi":[],"meaning_vi":"Con ếch"},
  {"character":"鼎","han_viet":"Đỉnh","onyomi":["テイ"],"kunyomi":["かなえ"],"meaning_vi":"Vạc, đỉnh"},
  {"character":"鼓","han_viet":"Cổ","onyomi":["コ"],"kunyomi":["つづみ"],"meaning_vi":"Trống"},
  {"character":"鼠","han_viet":"Thử","onyomi":["ソ"],"kunyomi":["ねずみ"],"meaning_vi":"Con chuột"},
  {"character":"鼻","han_viet":"Tỵ","onyomi":["ビ"],"kunyomi":["はな"],"meaning_vi":"Mũi"},
  {"character":"齊","han_viet":"Tề","onyomi":["セイ"],"kunyomi":[],"meaning_vi":"Đều, ngay ngắn"},
  {"character":"齒","han_viet":"Xỉ","onyomi":["シ"],"kunyomi":["は"],"meaning_vi":"Răng"},
  {"character":"龍","han_viet":"Long","onyomi":["リュウ"],"kunyomi":["たつ"],"meaning_vi":"Rồng"},
  {"character":"龜","han_viet":"Quy","onyomi":["キ"],"kunyomi":["かめ"],"meaning_vi":"Con rùa"},
  {"character":"龠","han_viet":"Dược","onyomi":["ヤク"],"kunyomi":[],"meaning_vi":"Ống sáo"},
]
