"""214 Kangxi Radicals (Bộ thủ) data - Part 1: Lessons 1-9 (1-stroke to 5-stroke)"""

RADICALS_1 = [
  {"character":"一","han_viet":"Nhất","onyomi":["イチ"],"kunyomi":["ひと-"],"meaning_vi":"Một"},
  {"character":"丨","han_viet":"Cổn","onyomi":["コン"],"kunyomi":[],"meaning_vi":"Nét sổ"},
  {"character":"丶","han_viet":"Chủ","onyomi":["チュ"],"kunyomi":[],"meaning_vi":"Nét chấm"},
  {"character":"丿","han_viet":"Phiệt","onyomi":["ヘツ"],"kunyomi":[],"meaning_vi":"Nét phẩy"},
  {"character":"乙","han_viet":"Ất","onyomi":["オツ"],"kunyomi":[],"meaning_vi":"Thứ hai, uốn"},
  {"character":"亅","han_viet":"Quyết","onyomi":["ケツ"],"kunyomi":[],"meaning_vi":"Nét móc"},
]

RADICALS_2 = [
  {"character":"二","han_viet":"Nhị","onyomi":["ニ"],"kunyomi":["ふた-"],"meaning_vi":"Hai"},
  {"character":"亠","han_viet":"Đầu","onyomi":["トウ"],"kunyomi":[],"meaning_vi":"Nắp, đầu"},
  {"character":"人","han_viet":"Nhân","onyomi":["ジン"],"kunyomi":["ひと"],"meaning_vi":"Người"},
  {"character":"儿","han_viet":"Nhi","onyomi":["ジン"],"kunyomi":[],"meaning_vi":"Chân người"},
  {"character":"入","han_viet":"Nhập","onyomi":["ニュウ"],"kunyomi":["い-る"],"meaning_vi":"Vào"},
  {"character":"八","han_viet":"Bát","onyomi":["ハチ"],"kunyomi":["や-"],"meaning_vi":"Tám"},
  {"character":"冂","han_viet":"Quynh","onyomi":["ケイ"],"kunyomi":[],"meaning_vi":"Vùng xa"},
  {"character":"冖","han_viet":"Mịch","onyomi":["ベキ"],"kunyomi":[],"meaning_vi":"Nắp đậy"},
  {"character":"冫","han_viet":"Băng","onyomi":["ヒョウ"],"kunyomi":[],"meaning_vi":"Băng, nước đá"},
  {"character":"几","han_viet":"Kỷ","onyomi":["キ"],"kunyomi":["つくえ"],"meaning_vi":"Cái bàn nhỏ"},
  {"character":"凵","han_viet":"Khảm","onyomi":["カン"],"kunyomi":[],"meaning_vi":"Hõm, lõm"},
  {"character":"刀","han_viet":"Đao","onyomi":["トウ"],"kunyomi":["かたな"],"meaning_vi":"Dao"},
  {"character":"力","han_viet":"Lực","onyomi":["リョク"],"kunyomi":["ちから"],"meaning_vi":"Sức mạnh"},
  {"character":"勹","han_viet":"Bao","onyomi":["ホウ"],"kunyomi":[],"meaning_vi":"Bọc, gói"},
  {"character":"匕","han_viet":"Tỉ","onyomi":["ヒ"],"kunyomi":[],"meaning_vi":"Cái thìa"},
  {"character":"匚","han_viet":"Phương","onyomi":["ホウ"],"kunyomi":[],"meaning_vi":"Hộp vuông"},
  {"character":"匸","han_viet":"Hệ","onyomi":["ケイ"],"kunyomi":[],"meaning_vi":"Che giấu"},
  {"character":"十","han_viet":"Thập","onyomi":["ジュウ"],"kunyomi":["とお"],"meaning_vi":"Mười"},
  {"character":"卜","han_viet":"Bốc","onyomi":["ボク"],"kunyomi":["うらな-う"],"meaning_vi":"Bói"},
  {"character":"卩","han_viet":"Tiết","onyomi":["セツ"],"kunyomi":[],"meaning_vi":"Con dấu, ấn"},
  {"character":"厂","han_viet":"Hán","onyomi":["カン"],"kunyomi":[],"meaning_vi":"Vách đá"},
  {"character":"厶","han_viet":"Tư","onyomi":["シ"],"kunyomi":[],"meaning_vi":"Riêng tư"},
  {"character":"又","han_viet":"Hựu","onyomi":["ユウ"],"kunyomi":["また"],"meaning_vi":"Lại, tay phải"},
]

RADICALS_3A = [
  {"character":"口","han_viet":"Khẩu","onyomi":["コウ"],"kunyomi":["くち"],"meaning_vi":"Miệng"},
  {"character":"囗","han_viet":"Vi","onyomi":["イ"],"kunyomi":[],"meaning_vi":"Bao vây"},
  {"character":"土","han_viet":"Thổ","onyomi":["ド"],"kunyomi":["つち"],"meaning_vi":"Đất"},
  {"character":"士","han_viet":"Sĩ","onyomi":["シ"],"kunyomi":[],"meaning_vi":"Kẻ sĩ"},
  {"character":"夂","han_viet":"Trĩ","onyomi":["チ"],"kunyomi":[],"meaning_vi":"Đi chậm"},
  {"character":"夊","han_viet":"Tuy","onyomi":["スイ"],"kunyomi":[],"meaning_vi":"Đi chậm"},
  {"character":"夕","han_viet":"Tịch","onyomi":["セキ"],"kunyomi":["ゆう"],"meaning_vi":"Chiều tối"},
  {"character":"大","han_viet":"Đại","onyomi":["ダイ"],"kunyomi":["おお-きい"],"meaning_vi":"To lớn"},
  {"character":"女","han_viet":"Nữ","onyomi":["ジョ"],"kunyomi":["おんな"],"meaning_vi":"Phụ nữ"},
  {"character":"子","han_viet":"Tử","onyomi":["シ"],"kunyomi":["こ"],"meaning_vi":"Con"},
  {"character":"宀","han_viet":"Miên","onyomi":["ベン"],"kunyomi":[],"meaning_vi":"Mái nhà"},
  {"character":"寸","han_viet":"Thốn","onyomi":["スン"],"kunyomi":[],"meaning_vi":"Tấc"},
  {"character":"小","han_viet":"Tiểu","onyomi":["ショウ"],"kunyomi":["ちい-さい"],"meaning_vi":"Nhỏ"},
  {"character":"尢","han_viet":"Uông","onyomi":["オウ"],"kunyomi":[],"meaning_vi":"Què, yếu"},
  {"character":"尸","han_viet":"Thi","onyomi":["シ"],"kunyomi":[],"meaning_vi":"Xác chết, thây"},
]

RADICALS_3B = [
  {"character":"屮","han_viet":"Triệt","onyomi":["テツ"],"kunyomi":[],"meaning_vi":"Mầm cây"},
  {"character":"山","han_viet":"Sơn","onyomi":["サン"],"kunyomi":["やま"],"meaning_vi":"Núi"},
  {"character":"巛","han_viet":"Xuyên","onyomi":["セン"],"kunyomi":["かわ"],"meaning_vi":"Sông"},
  {"character":"工","han_viet":"Công","onyomi":["コウ"],"kunyomi":[],"meaning_vi":"Thợ, công"},
  {"character":"己","han_viet":"Kỷ","onyomi":["キ"],"kunyomi":["おのれ"],"meaning_vi":"Bản thân"},
  {"character":"巾","han_viet":"Cân","onyomi":["キン"],"kunyomi":[],"meaning_vi":"Khăn"},
  {"character":"干","han_viet":"Can","onyomi":["カン"],"kunyomi":["ほ-す"],"meaning_vi":"Khô, can"},
  {"character":"幺","han_viet":"Yêu","onyomi":["ヨウ"],"kunyomi":[],"meaning_vi":"Nhỏ, sợi nhỏ"},
  {"character":"广","han_viet":"Nghiễm","onyomi":["ゲン"],"kunyomi":[],"meaning_vi":"Mái hiên"},
  {"character":"廴","han_viet":"Dẫn","onyomi":["イン"],"kunyomi":[],"meaning_vi":"Bước dài"},
  {"character":"廾","han_viet":"Củng","onyomi":["キョウ"],"kunyomi":[],"meaning_vi":"Hai tay chắp"},
  {"character":"弋","han_viet":"Dặc","onyomi":["ヨク"],"kunyomi":[],"meaning_vi":"Bắn, cọc"},
  {"character":"弓","han_viet":"Cung","onyomi":["キュウ"],"kunyomi":["ゆみ"],"meaning_vi":"Cây cung"},
  {"character":"彐","han_viet":"Kệ","onyomi":["ケイ"],"kunyomi":[],"meaning_vi":"Đầu lợn"},
  {"character":"彡","han_viet":"Sam","onyomi":["サン"],"kunyomi":[],"meaning_vi":"Lông, vằn"},
  {"character":"彳","han_viet":"Xích","onyomi":["テキ"],"kunyomi":[],"meaning_vi":"Bước nhỏ"},
]

RADICALS_4A = [
  {"character":"心","han_viet":"Tâm","onyomi":["シン"],"kunyomi":["こころ"],"meaning_vi":"Trái tim"},
  {"character":"戈","han_viet":"Qua","onyomi":["カ"],"kunyomi":[],"meaning_vi":"Cây giáo"},
  {"character":"戶","han_viet":"Hộ","onyomi":["コ"],"kunyomi":["と"],"meaning_vi":"Cửa, nhà"},
  {"character":"手","han_viet":"Thủ","onyomi":["シュ"],"kunyomi":["て"],"meaning_vi":"Tay"},
  {"character":"支","han_viet":"Chi","onyomi":["シ"],"kunyomi":[],"meaning_vi":"Nhánh, chống"},
  {"character":"攴","han_viet":"Phộc","onyomi":["ボク"],"kunyomi":[],"meaning_vi":"Đánh nhẹ"},
  {"character":"文","han_viet":"Văn","onyomi":["ブン"],"kunyomi":[],"meaning_vi":"Văn chương"},
  {"character":"斗","han_viet":"Đẩu","onyomi":["ト"],"kunyomi":[],"meaning_vi":"Đấu (đo)"},
  {"character":"斤","han_viet":"Cân","onyomi":["キン"],"kunyomi":[],"meaning_vi":"Rìu, cân"},
  {"character":"方","han_viet":"Phương","onyomi":["ホウ"],"kunyomi":["かた"],"meaning_vi":"Phương hướng"},
  {"character":"无","han_viet":"Vô","onyomi":["ブ"],"kunyomi":["な-い"],"meaning_vi":"Không có"},
  {"character":"日","han_viet":"Nhật","onyomi":["ニチ"],"kunyomi":["ひ"],"meaning_vi":"Mặt trời, ngày"},
  {"character":"曰","han_viet":"Viết","onyomi":["エツ"],"kunyomi":[],"meaning_vi":"Rằng, nói"},
  {"character":"月","han_viet":"Nguyệt","onyomi":["ゲツ"],"kunyomi":["つき"],"meaning_vi":"Mặt trăng"},
  {"character":"木","han_viet":"Mộc","onyomi":["モク"],"kunyomi":["き"],"meaning_vi":"Cây, gỗ"},
  {"character":"欠","han_viet":"Khiếm","onyomi":["ケツ"],"kunyomi":["か-ける"],"meaning_vi":"Thiếu"},
  {"character":"止","han_viet":"Chỉ","onyomi":["シ"],"kunyomi":["と-まる"],"meaning_vi":"Dừng lại"},
]

RADICALS_4B = [
  {"character":"歹","han_viet":"Đãi","onyomi":["タイ"],"kunyomi":[],"meaning_vi":"Xương, chết"},
  {"character":"殳","han_viet":"Thù","onyomi":["シュ"],"kunyomi":[],"meaning_vi":"Binh khí"},
  {"character":"毋","han_viet":"Vô","onyomi":["ブ"],"kunyomi":[],"meaning_vi":"Chớ, đừng"},
  {"character":"比","han_viet":"Tỉ","onyomi":["ヒ"],"kunyomi":["くら-べる"],"meaning_vi":"So sánh"},
  {"character":"毛","han_viet":"Mao","onyomi":["モウ"],"kunyomi":["け"],"meaning_vi":"Lông"},
  {"character":"氏","han_viet":"Thị","onyomi":["シ"],"kunyomi":[],"meaning_vi":"Họ, dòng"},
  {"character":"气","han_viet":"Khí","onyomi":["キ"],"kunyomi":[],"meaning_vi":"Hơi, khí"},
  {"character":"水","han_viet":"Thủy","onyomi":["スイ"],"kunyomi":["みず"],"meaning_vi":"Nước"},
  {"character":"火","han_viet":"Hỏa","onyomi":["カ"],"kunyomi":["ひ"],"meaning_vi":"Lửa"},
  {"character":"爪","han_viet":"Trảo","onyomi":["ソウ"],"kunyomi":["つめ"],"meaning_vi":"Móng vuốt"},
  {"character":"父","han_viet":"Phụ","onyomi":["フ"],"kunyomi":["ちち"],"meaning_vi":"Cha"},
  {"character":"爻","han_viet":"Hào","onyomi":["コウ"],"kunyomi":[],"meaning_vi":"Hào (quẻ)"},
  {"character":"爿","han_viet":"Tường","onyomi":["ショウ"],"kunyomi":[],"meaning_vi":"Mảnh gỗ"},
  {"character":"片","han_viet":"Phiến","onyomi":["ヘン"],"kunyomi":["かた"],"meaning_vi":"Mảnh, miếng"},
  {"character":"牙","han_viet":"Nha","onyomi":["ガ"],"kunyomi":["きば"],"meaning_vi":"Răng nanh"},
  {"character":"牛","han_viet":"Ngưu","onyomi":["ギュウ"],"kunyomi":["うし"],"meaning_vi":"Con bò"},
  {"character":"犬","han_viet":"Khuyển","onyomi":["ケン"],"kunyomi":["いぬ"],"meaning_vi":"Con chó"},
]

RADICALS_5 = [
  {"character":"玄","han_viet":"Huyền","onyomi":["ゲン"],"kunyomi":[],"meaning_vi":"Huyền bí"},
  {"character":"玉","han_viet":"Ngọc","onyomi":["ギョク"],"kunyomi":["たま"],"meaning_vi":"Ngọc"},
  {"character":"瓜","han_viet":"Qua","onyomi":["カ"],"kunyomi":["うり"],"meaning_vi":"Quả dưa"},
  {"character":"瓦","han_viet":"Ngõa","onyomi":["ガ"],"kunyomi":["かわら"],"meaning_vi":"Ngói"},
  {"character":"甘","han_viet":"Cam","onyomi":["カン"],"kunyomi":["あま-い"],"meaning_vi":"Ngọt"},
  {"character":"生","han_viet":"Sinh","onyomi":["セイ"],"kunyomi":["い-きる"],"meaning_vi":"Sống, sinh"},
  {"character":"用","han_viet":"Dụng","onyomi":["ヨウ"],"kunyomi":["もち-いる"],"meaning_vi":"Dùng"},
  {"character":"田","han_viet":"Điền","onyomi":["デン"],"kunyomi":["た"],"meaning_vi":"Ruộng"},
  {"character":"疋","han_viet":"Thất","onyomi":["ヒキ"],"kunyomi":[],"meaning_vi":"Cuộn vải"},
  {"character":"疒","han_viet":"Nạch","onyomi":["ダク"],"kunyomi":[],"meaning_vi":"Bệnh"},
  {"character":"癶","han_viet":"Bát","onyomi":["ハツ"],"kunyomi":[],"meaning_vi":"Bước chân"},
  {"character":"白","han_viet":"Bạch","onyomi":["ハク"],"kunyomi":["しろ"],"meaning_vi":"Trắng"},
  {"character":"皮","han_viet":"Bì","onyomi":["ヒ"],"kunyomi":["かわ"],"meaning_vi":"Da"},
  {"character":"皿","han_viet":"Mãnh","onyomi":["ベイ"],"kunyomi":["さら"],"meaning_vi":"Cái đĩa"},
  {"character":"目","han_viet":"Mục","onyomi":["モク"],"kunyomi":["め"],"meaning_vi":"Mắt"},
  {"character":"矛","han_viet":"Mâu","onyomi":["ム"],"kunyomi":["ほこ"],"meaning_vi":"Cây mâu"},
  {"character":"矢","han_viet":"Thỉ","onyomi":["シ"],"kunyomi":["や"],"meaning_vi":"Mũi tên"},
  {"character":"石","han_viet":"Thạch","onyomi":["セキ"],"kunyomi":["いし"],"meaning_vi":"Đá"},
  {"character":"示","han_viet":"Thị","onyomi":["シ"],"kunyomi":["しめ-す"],"meaning_vi":"Chỉ bảo"},
  {"character":"禸","han_viet":"Nhựu","onyomi":["ジュウ"],"kunyomi":[],"meaning_vi":"Dấu chân thú"},
  {"character":"禾","han_viet":"Hòa","onyomi":["カ"],"kunyomi":["いね"],"meaning_vi":"Lúa"},
  {"character":"穴","han_viet":"Huyệt","onyomi":["ケツ"],"kunyomi":["あな"],"meaning_vi":"Hang, lỗ"},
  {"character":"立","han_viet":"Lập","onyomi":["リツ"],"kunyomi":["た-つ"],"meaning_vi":"Đứng"},
]
